import {
  AmlAlert,
  AmlInvestigation,
  AmlRule,
  AmlScoreBreakdown,
  AmlTransaction,
  BusinessKybProfile,
  CustomerKycProfile,
  MicrotransactionCluster,
  SarDraft,
  ScreeningCheck,
} from "./aml.types";
import { AuditEvent, GraphEdge, GraphNode } from "../../domain";

const now = new Date();
const ago = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();
const daysAgo = (days: number) => ago(days * 24 * 60);

const lowScores: AmlScoreBreakdown = {
  deterministicRules: 12,
  mlAnomaly: 18,
  behaviouralProfile: 16,
  identityGraph: 14,
  consortiumIntelligence: 0,
  amlSanctions: 0,
  customerKyc: 12,
  businessKyb: 0,
  deviceRisk: 18,
  geographicRisk: 12,
  beneficiaryRisk: 8,
  transactionVelocity: 10,
  microtransactionCluster: 4,
  historicalOutcomes: 8,
};

const highScores = (microtransactionCluster = 78): AmlScoreBreakdown => ({
  deterministicRules: 76,
  mlAnomaly: 72,
  behaviouralProfile: 68,
  identityGraph: 74,
  consortiumIntelligence: 42,
  amlSanctions: 54,
  customerKyc: 62,
  businessKyb: 58,
  deviceRisk: 69,
  geographicRisk: 55,
  beneficiaryRisk: 71,
  transactionVelocity: 83,
  microtransactionCluster,
  historicalOutcomes: 64,
});

export const amlCustomers: CustomerKycProfile[] = [
  {
    id: "cust-salary-001",
    fullLegalName: "Nia Mensa",
    previousNames: [],
    dateOfBirth: "1992-04-18",
    nationality: "Ghanaian",
    countryOfResidence: "GH",
    residentialAddress: "Fictional Ridge Residence, Accra",
    telephoneNumber: "+233-000-0101",
    emailAddress: "nia.mensa@example.test",
    occupation: "Teacher",
    employer: "Fictional Coast School",
    expectedAccountPurpose: "Salary, household bills, savings, and family support.",
    expectedMonthlyIncome: 1850,
    expectedTransactionVolume: 2600,
    expectedPaymentCorridors: ["GH-GH", "GH-NG"],
    expectedCounterparties: ["employer", "utilities", "family"],
    sourceOfFunds: "Salary",
    sourceOfWealth: "Employment income and savings",
    identityDocument: { type: "national_id", issuingCountry: "GH", maskedNumber: "GHA-****-2190", expiresAt: "2029-06-30" },
    addressVerificationStatus: "passed",
    livenessStatus: "passed",
    deviceInformation: ["dev-salary-1", "sim-hash-salary-1"],
    taxResidency: ["GH"],
    customerRiskScore: 18,
    kycStatus: "passed",
    lastReviewDate: daysAgo(65),
    nextReviewDate: daysAgo(-300),
    checks: [
      { name: "Identity verification", status: "passed", risk: "low", evidence: "Test identity check matched declared name and DOB." },
      { name: "Sanctions", status: "test_result", risk: "low", evidence: "No seeded list match in test data." },
      { name: "Adverse media", status: "test_result", risk: "low", evidence: "No adverse-media indicator in test corpus." },
    ],
    edd: {
      required: false,
      seniorApproval: "approved",
      relationshipReason: "Retail banking relationship.",
      transactionPurpose: "Household payments.",
      supportingDocuments: ["salary-letter-test.pdf"],
      monitoringFrequency: "standard annual review",
      temporaryRestrictions: [],
      investigatorNotes: ["Normal salary and household payment pattern."],
    },
  },
  {
    id: "cust-wallet-042",
    fullLegalName: "Amara Bello",
    previousNames: [],
    dateOfBirth: "1988-11-02",
    nationality: "Nigerian",
    countryOfResidence: "NG",
    residentialAddress: "Fictional Yaba Road, Lagos",
    telephoneNumber: "+234-000-1042",
    emailAddress: "amara.bello@example.test",
    occupation: "Market trader",
    employer: "Self-employed",
    expectedAccountPurpose: "Mobile-money business takings and supplier payments.",
    expectedMonthlyIncome: 3200,
    expectedTransactionVolume: 9800,
    expectedPaymentCorridors: ["NG-NG", "NG-GH"],
    expectedCounterparties: ["suppliers", "mobile-money agents", "customers"],
    sourceOfFunds: "Market trading proceeds",
    sourceOfWealth: "Small-business income",
    identityDocument: { type: "voter_id", issuingCountry: "NG", maskedNumber: "NGA-****-4202", expiresAt: "2028-03-12" },
    addressVerificationStatus: "passed",
    livenessStatus: "passed",
    deviceInformation: ["dev-shared-991", "sim-hash-4202"],
    taxResidency: ["NG"],
    customerRiskScore: 71,
    kycStatus: "edd_required",
    lastReviewDate: daysAgo(250),
    nextReviewDate: daysAgo(-8),
    checks: [
      { name: "Duplicate identity detection", status: "manual_verification_required", risk: "medium", evidence: "Shared handset appears across unrelated wallets; mobile-money use itself is not treated as suspicious." },
      { name: "PEP/RCA", status: "test_result", risk: "medium", evidence: "Relative-and-close-associate test match requires reviewer disposition." },
      { name: "Source of funds", status: "information_requested", risk: "high", evidence: "Turnover and cash-in volume have diverged from declared baseline." },
    ],
    edd: {
      required: true,
      seniorApproval: "pending",
      relationshipReason: "Continue wallet access with restricted cash-out limit while SOF evidence is gathered.",
      transactionPurpose: "Supplier settlement and market takings.",
      supportingDocuments: ["market-stall-licence-test.pdf", "supplier-ledger-test.csv"],
      monitoringFrequency: "30-day EDD review",
      temporaryRestrictions: ["cash-out limit 40% below current threshold", "manual review on new beneficiaries"],
      investigatorNotes: ["EDD triggered by behaviour and shared-device context, not nationality or mobile-money channel."],
    },
  },
  {
    id: "cust-remit-777",
    fullLegalName: "Laila Haddad",
    previousNames: ["Laila H."],
    dateOfBirth: "1979-01-22",
    nationality: "Moroccan",
    countryOfResidence: "MA",
    residentialAddress: "Fictional Maarif Avenue, Casablanca",
    telephoneNumber: "+212-000-0777",
    emailAddress: "laila.haddad@example.test",
    occupation: "Import coordinator",
    employer: "Atlas Test Logistics",
    expectedAccountPurpose: "Salary and family remittances.",
    expectedMonthlyIncome: 4100,
    expectedTransactionVolume: 7000,
    expectedPaymentCorridors: ["MA-EG", "MA-GH"],
    expectedCounterparties: ["family", "registered exchange partner"],
    sourceOfFunds: "Employment income",
    sourceOfWealth: "Employment savings",
    identityDocument: { type: "passport", issuingCountry: "MA", maskedNumber: "MAR-****-7770", expiresAt: "2027-12-10" },
    addressVerificationStatus: "passed",
    livenessStatus: "passed",
    deviceInformation: ["dev-remit-777"],
    taxResidency: ["MA"],
    customerRiskScore: 64,
    kycStatus: "referred",
    lastReviewDate: daysAgo(120),
    nextReviewDate: daysAgo(15),
    checks: [
      { name: "Sanctions false-positive", status: "test_result", risk: "medium", evidence: "Name similarity to a list entry; DOB and nationality do not match." },
      { name: "Adverse media", status: "mock_result", risk: "low", evidence: "No high-confidence adverse-media evidence." },
    ],
    edd: {
      required: true,
      seniorApproval: "pending",
      relationshipReason: "Resolve false-positive screening and confirm remittance purpose.",
      transactionPurpose: "Family support remittances.",
      supportingDocuments: ["employer-letter-test.pdf"],
      monitoringFrequency: "quarterly until false-positive disposition is closed",
      temporaryRestrictions: ["manual review on new cross-border beneficiaries"],
      investigatorNotes: ["False-positive handling requires human disposition."],
    },
  },
  {
    id: "cust-sanction-901",
    fullLegalName: "Kito Dlamini",
    previousNames: [],
    dateOfBirth: "1984-08-09",
    nationality: "Fictional",
    countryOfResidence: "ZA",
    residentialAddress: "Fictional West Road, Johannesburg",
    telephoneNumber: "+27-000-0901",
    emailAddress: "kito.dlamini@example.test",
    occupation: "Consultant",
    employer: "Independent",
    expectedAccountPurpose: "Consulting income.",
    expectedMonthlyIncome: 9000,
    expectedTransactionVolume: 12000,
    expectedPaymentCorridors: ["ZA-ZA", "ZA-KE"],
    expectedCounterparties: ["business clients"],
    sourceOfFunds: "Consulting invoices",
    sourceOfWealth: "Consulting income",
    identityDocument: { type: "passport", issuingCountry: "ZA", maskedNumber: "ZAF-****-9010", expiresAt: "2026-10-15" },
    addressVerificationStatus: "referred",
    livenessStatus: "passed",
    deviceInformation: ["dev-sanction-901"],
    taxResidency: ["ZA"],
    customerRiskScore: 94,
    kycStatus: "referred",
    lastReviewDate: daysAgo(20),
    nextReviewDate: daysAgo(1),
    checks: [
      { name: "Sanctions", status: "test_result", risk: "critical", evidence: "High-confidence sanctions test match. Human review required before irreversible action." },
      { name: "Source of wealth", status: "manual_verification_required", risk: "high", evidence: "Consulting invoices do not explain accumulated incoming value." },
    ],
    edd: {
      required: true,
      seniorApproval: "pending",
      relationshipReason: "Restrict and investigate high-confidence screening test match.",
      transactionPurpose: "Consulting receipts.",
      supportingDocuments: ["invoice-bundle-test.zip"],
      monitoringFrequency: "continuous until disposition",
      temporaryRestrictions: ["hold outbound transfers", "block new beneficiary creation"],
      investigatorNotes: ["Do not file SAR automatically; MLRO-equivalent review required."],
    },
  },
];

export const amlBusinesses: BusinessKybProfile[] = [
  {
    id: "bus-market-010",
    legalName: "Kijani Market Services Ltd",
    tradingName: "Kijani Market",
    companyNumber: "KE-FICT-010",
    incorporationDate: "2018-05-10",
    incorporationCountry: "KE",
    registeredAddress: "Fictional River Road, Nairobi",
    tradingAddress: "Fictional Market Lane, Nairobi",
    businessType: "private_company",
    industry: "Retail market services",
    website: "https://kijani-market.example.test",
    emailDomain: "kijani-market.example.test",
    declaredTurnover: 350000,
    expectedTransactionVolume: 42000,
    countriesOfOperation: ["KE"],
    regulatoryStatus: "registered",
    directors: [{ id: "dir-010-a", name: "Musa Kariuki", country: "KE", risk: "low" }],
    shareholders: [{ id: "shr-010-a", name: "Musa Kariuki", ownershipPct: 80, risk: "low" }],
    ultimateBeneficialOwners: [{ id: "ubo-010-a", name: "Musa Kariuki", ownershipPct: 80, risk: "low" }],
    parentEntities: [],
    subsidiaries: [],
    sourceOfBusinessFunds: "Retail service revenue",
    businessRelationshipPurpose: "Merchant settlement and supplier payments",
    licences: ["county-trading-licence-test"],
    taxInformation: "KE PIN ****010",
    kybStatus: "passed",
    riskScore: 24,
    lastReviewDate: daysAgo(80),
    nextReviewDate: daysAgo(-280),
    indicators: ["Normal merchant settlement pattern"],
    ownershipGraph: {
      nodes: [
        { id: "bus-market-010", type: "business", label: "Kijani Market", risk: 24, x: 50, y: 50 },
        { id: "ubo-010-a", type: "ubo", label: "UBO hash 010A", risk: 18, x: 28, y: 38 },
        { id: "addr-010", type: "address", label: "Nairobi address", risk: 20, x: 70, y: 42 },
      ],
      edges: [
        { id: "edge-kyb-010-1", source: "ubo-010-a", target: "bus-market-010", relationship: "controls", weight: 0.8 },
        { id: "edge-kyb-010-2", source: "bus-market-010", target: "addr-010", relationship: "registered_at", weight: 0.7 },
      ],
    },
  },
  {
    id: "bus-dormant-303",
    legalName: "Baobab Import Traders Ltd",
    tradingName: "Baobab Imports",
    companyNumber: "GH-FICT-303",
    incorporationDate: "2024-10-02",
    incorporationCountry: "GH",
    registeredAddress: "Fictional Shared Office 44, Accra",
    tradingAddress: "Fictional Shared Office 44, Accra",
    businessType: "private_company",
    industry: "Import and wholesale",
    website: "https://baobab-imports.example.test",
    emailDomain: "generic-mail.example.test",
    declaredTurnover: 90000,
    expectedTransactionVolume: 15000,
    countriesOfOperation: ["GH", "NG", "CI"],
    regulatoryStatus: "registered",
    directors: [{ id: "dir-303-a", name: "Fictional Nominee A", country: "GH", risk: "high" }],
    shareholders: [
      { id: "shr-303-a", name: "Layer One Holdings", ownershipPct: 60, risk: "high" },
      { id: "shr-303-b", name: "Nominee Trust 303", ownershipPct: 40, risk: "high" },
    ],
    ultimateBeneficialOwners: [],
    parentEntities: ["Layer One Holdings", "Nominee Trust 303"],
    subsidiaries: [],
    sourceOfBusinessFunds: "Stated import revenue",
    businessRelationshipPurpose: "Supplier payments and settlement",
    licences: [],
    taxInformation: "GH TIN ****303",
    kybStatus: "edd_required",
    riskScore: 86,
    lastReviewDate: daysAgo(210),
    nextReviewDate: daysAgo(12),
    indicators: ["No identifiable UBO", "Complex ownership layering", "Dormant-company activity", "Virtual-office concentration", "Declared-turnover mismatch"],
    ownershipGraph: {
      nodes: [
        { id: "bus-dormant-303", type: "business", label: "Baobab Imports", risk: 86, x: 48, y: 52 },
        { id: "dir-303-a", type: "director", label: "Nominee director", risk: 78, x: 26, y: 32 },
        { id: "shr-303-a", type: "shareholder", label: "Layer One Holdings", risk: 82, x: 28, y: 70 },
        { id: "addr-shared-44", type: "address", label: "Shared office 44", risk: 74, x: 72, y: 38 },
        { id: "dev-shared-991", type: "device", label: "Shared handset", risk: 82, x: 74, y: 72 },
      ],
      edges: [
        { id: "edge-kyb-303-1", source: "dir-303-a", target: "bus-dormant-303", relationship: "directs", weight: 0.7 },
        { id: "edge-kyb-303-2", source: "shr-303-a", target: "bus-dormant-303", relationship: "owns", weight: 0.6 },
        { id: "edge-kyb-303-3", source: "bus-dormant-303", target: "addr-shared-44", relationship: "registered_at", weight: 0.8 },
        { id: "edge-kyb-303-4", source: "bus-dormant-303", target: "dev-shared-991", relationship: "used_on", weight: 0.72 },
      ],
    },
  },
  {
    id: "bus-agent-909",
    legalName: "Moyo Cash Agent Network Ltd",
    tradingName: "Moyo Cash",
    companyNumber: "TZ-FICT-909",
    incorporationDate: "2020-09-17",
    incorporationCountry: "TZ",
    registeredAddress: "Fictional Ferry Street, Dar es Salaam",
    tradingAddress: "Fictional Ferry Street, Dar es Salaam",
    businessType: "mobile_money_agent_network",
    industry: "Mobile-money agency",
    website: "https://moyo-cash.example.test",
    emailDomain: "moyo-cash.example.test",
    declaredTurnover: 700000,
    expectedTransactionVolume: 110000,
    countriesOfOperation: ["TZ", "KE"],
    regulatoryStatus: "licensed agent network",
    directors: [{ id: "dir-909-a", name: "Zuri Mwinyi", country: "TZ", risk: "medium" }],
    shareholders: [{ id: "shr-909-a", name: "Zuri Mwinyi", ownershipPct: 51, risk: "medium" }],
    ultimateBeneficialOwners: [{ id: "ubo-909-a", name: "Zuri Mwinyi", ownershipPct: 51, risk: "medium" }],
    parentEntities: [],
    subsidiaries: ["Moyo Cash Agent 19"],
    sourceOfBusinessFunds: "Agent commissions and float management",
    businessRelationshipPurpose: "Cash-in, cash-out, and wallet settlement",
    licences: ["mobile-money-agent-licence-test"],
    taxInformation: "TZ TIN ****909",
    kybStatus: "referred",
    riskScore: 67,
    lastReviewDate: daysAgo(170),
    nextReviewDate: daysAgo(18),
    indicators: ["Agent collusion indicators", "Multiple small deposits followed by consolidated cash-out", "Shared handset use"],
    ownershipGraph: {
      nodes: [
        { id: "bus-agent-909", type: "business", label: "Moyo Cash", risk: 67, x: 52, y: 52 },
        { id: "ubo-909-a", type: "ubo", label: "UBO hash 909A", risk: 48, x: 28, y: 42 },
        { id: "wallet-agent-19", type: "wallet", label: "Agent wallet 19", risk: 79, x: 76, y: 42 },
        { id: "dev-agent-19", type: "device", label: "Agent handset 19", risk: 78, x: 76, y: 70 },
      ],
      edges: [
        { id: "edge-kyb-909-1", source: "ubo-909-a", target: "bus-agent-909", relationship: "controls", weight: 0.51 },
        { id: "edge-kyb-909-2", source: "bus-agent-909", target: "wallet-agent-19", relationship: "owns", weight: 0.82 },
        { id: "edge-kyb-909-3", source: "wallet-agent-19", target: "dev-agent-19", relationship: "used_on", weight: 0.86 },
      ],
    },
  },
];

const baseTransaction = (
  id: string,
  overrides: Partial<AmlTransaction>,
): AmlTransaction => ({
  id,
  eventId: `evt-${id}`,
  institution: "African Trust Bank",
  customerId: "cust-wallet-042",
  businessId: undefined,
  accountId: "acct-wallet-042",
  walletId: "wallet-042",
  sender: "wallet-042",
  receiver: "beneficiary-test",
  beneficiary: "beneficiary-test",
  merchant: "Moyo Cash",
  amount: 95,
  currency: "USD",
  baseCurrencyEquivalent: 95,
  originCountry: "NG",
  destinationCountry: "NG",
  channel: "mobile_money",
  paymentMethod: "wallet_to_wallet",
  deviceId: "dev-shared-991",
  ipAddress: "198.51.100.42",
  phoneHash: "phone-hash-4202",
  addressHash: "addr-hash-yaba",
  beneficialOwnerId: undefined,
  description: "Seeded test transaction",
  direction: "outgoing",
  timestamp: ago(25),
  status: "review",
  fraudRisk: 68,
  amlRisk: 74,
  unifiedRisk: 72,
  decision: "review",
  rulesTriggered: ["rule-structuring-24h"],
  alertStatus: "new",
  componentScores: highScores(),
  explainability: [
    { feature: "microtransaction_cluster", impact: 78, direction: "risk_increase", evidence: "Multiple low-value transfers formed a cluster inside the rolling window." },
    { feature: "shared_device", impact: 58, direction: "risk_increase", evidence: "Device appears across unrelated wallets." },
  ],
  linkedTransactionIds: [],
  linkedDevices: ["dev-shared-991"],
  linkedIpAddresses: ["198.51.100.42"],
  linkedAccounts: ["acct-wallet-042"],
  sharedBeneficiaries: ["beneficiary-test"],
  historicalAlerts: [],
  recommendedAction: "Review transaction cluster with KYC baseline and graph context.",
  ...overrides,
});

export const amlTransactions: AmlTransaction[] = [
  baseTransaction("txn-normal-salary-001", {
    customerId: "cust-salary-001",
    accountId: "acct-salary-001",
    walletId: undefined,
    sender: "employer-payroll",
    receiver: "acct-salary-001",
    beneficiary: "Nia Mensa",
    merchant: undefined,
    amount: 1850,
    baseCurrencyEquivalent: 1850,
    direction: "incoming",
    timestamp: ago(8 * 60),
    status: "approved",
    fraudRisk: 14,
    amlRisk: 10,
    unifiedRisk: 12,
    decision: "approve",
    rulesTriggered: [],
    alertStatus: "none",
    componentScores: lowScores,
    explainability: [{ feature: "baseline", impact: 8, direction: "risk_decrease", evidence: "Salary payment matches expected employer and amount range." }],
    recommendedAction: "Approve and continue standard monitoring.",
    description: "Normal salary payment",
  }),
  baseTransaction("txn-normal-mobile-002", {
    amount: 34,
    baseCurrencyEquivalent: 34,
    receiver: "utility-wallet",
    beneficiary: "Utility provider",
    timestamp: ago(260),
    status: "approved",
    fraudRisk: 18,
    amlRisk: 16,
    unifiedRisk: 17,
    decision: "approve",
    rulesTriggered: [],
    alertStatus: "none",
    componentScores: lowScores,
    explainability: [{ feature: "mobile_money_baseline", impact: 10, direction: "risk_decrease", evidence: "Routine mobile-money usage matches customer and peer-group baseline." }],
    recommendedAction: "Approve.",
    description: "Normal mobile-money household payment",
  }),
  ...[0, 1, 2, 3, 4].map((index) =>
    baseTransaction(`txn-struct-${index + 1}`, {
      amount: 980 + index * 3,
      baseCurrencyEquivalent: 980 + index * 3,
      receiver: "acct-struct-beneficiary",
      beneficiary: "New beneficiary hash",
      timestamp: ago(40 - index * 5),
      description: "Repeated small payment below internal review threshold",
      rulesTriggered: ["rule-structuring-24h", "rule-threshold-avoidance"],
      linkedTransactionIds: ["txn-struct-1", "txn-struct-2", "txn-struct-3", "txn-struct-4", "txn-struct-5"].filter((item) => item !== `txn-struct-${index + 1}`),
    }),
  ),
  ...[0, 1, 2, 3].map((index) =>
    baseTransaction(`txn-fanin-${index + 1}`, {
      customerId: `cust-fanin-${index + 1}`,
      accountId: `acct-fanin-${index + 1}`,
      walletId: `wallet-fanin-${index + 1}`,
      sender: `wallet-fanin-${index + 1}`,
      receiver: "wallet-collector-88",
      beneficiary: "Collector wallet hash",
      amount: 180 + index * 12,
      baseCurrencyEquivalent: 180 + index * 12,
      timestamp: ago(95 - index * 12),
      deviceId: index < 2 ? "dev-shared-991" : `dev-fanin-${index + 1}`,
      ipAddress: index < 2 ? "198.51.100.42" : `198.51.100.${80 + index}`,
      description: "Many wallets funding one recipient",
      rulesTriggered: ["rule-fan-in", "rule-shared-device"],
    }),
  ),
  ...[0, 1, 2, 3].map((index) =>
    baseTransaction(`txn-fanout-${index + 1}`, {
      sender: "wallet-distributor-11",
      receiver: `beneficiary-new-${index + 1}`,
      beneficiary: `New beneficiary ${index + 1}`,
      amount: 210 + index * 9,
      timestamp: ago(150 - index * 7),
      description: "One wallet distributing funds to many beneficiaries",
      rulesTriggered: ["rule-fan-out", "rule-new-beneficiary"],
      sharedBeneficiaries: [`beneficiary-new-${index + 1}`],
    }),
  ),
  baseTransaction("txn-pass-through-in", {
    customerId: "cust-wallet-042",
    amount: 4400,
    baseCurrencyEquivalent: 4400,
    sender: "cash-agent-19",
    receiver: "wallet-042",
    beneficiary: "Amara Bello",
    direction: "incoming",
    timestamp: ago(73),
    description: "Cash-in before rapid outgoing movement",
    rulesTriggered: ["rule-rapid-pass-through"],
  }),
  baseTransaction("txn-pass-through-out", {
    amount: 4310,
    baseCurrencyEquivalent: 4310,
    sender: "wallet-042",
    receiver: "bank-acct-external-77",
    beneficiary: "External bank account",
    direction: "outgoing",
    channel: "bank",
    paymentMethod: "wallet_to_bank",
    timestamp: ago(66),
    description: "Wallet-to-bank pass-through after cash-in",
    rulesTriggered: ["rule-rapid-pass-through", "rule-low-residual-balance"],
  }),
  baseTransaction("txn-dormant-business-001", {
    customerId: "cust-business-operator",
    businessId: "bus-dormant-303",
    amount: 8700,
    baseCurrencyEquivalent: 8700,
    sender: "bus-dormant-303",
    receiver: "supplier-new-77",
    beneficiary: "Supplier hash",
    merchant: "Baobab Imports",
    channel: "api",
    paymentMethod: "bank_to_wallet",
    timestamp: ago(210),
    fraudRisk: 74,
    amlRisk: 82,
    unifiedRisk: 79,
    rulesTriggered: ["rule-dormant-reactivation", "rule-turnover-mismatch"],
    description: "Dormant business reactivation with turnover mismatch",
  }),
  baseTransaction("txn-device-change-001", {
    amount: 2500,
    baseCurrencyEquivalent: 2500,
    receiver: "beneficiary-sim-change",
    beneficiary: "Beneficiary after SIM change",
    timestamp: ago(18),
    rulesTriggered: ["rule-sim-device-change", "rule-new-beneficiary"],
    description: "SIM/device change followed by unusual payment",
  }),
  baseTransaction("txn-agent-collusion-001", {
    customerId: "cust-agent-operator",
    businessId: "bus-agent-909",
    accountId: "acct-agent-909",
    walletId: "wallet-agent-19",
    sender: "wallet-agent-19",
    receiver: "wallet-consolidator-19",
    beneficiary: "Consolidator wallet",
    amount: 1250,
    baseCurrencyEquivalent: 1250,
    channel: "cash_agent",
    paymentMethod: "cash_out",
    deviceId: "dev-agent-19",
    ipAddress: "198.51.100.119",
    timestamp: ago(32),
    rulesTriggered: ["rule-mobile-money-consolidation", "rule-agent-collusion"],
    description: "Multiple small deposits followed by consolidated cash-out",
  }),
  baseTransaction("txn-sanction-test-001", {
    customerId: "cust-sanction-901",
    accountId: "acct-sanction-901",
    walletId: undefined,
    sender: "acct-sanction-901",
    receiver: "counterparty-screening-hit",
    beneficiary: "Counterparty screening hit",
    amount: 6900,
    baseCurrencyEquivalent: 6900,
    channel: "bank",
    paymentMethod: "bank_transfer",
    originCountry: "ZA",
    destinationCountry: "KE",
    timestamp: ago(12),
    fraudRisk: 70,
    amlRisk: 95,
    unifiedRisk: 88,
    decision: "hold",
    status: "held",
    rulesTriggered: ["rule-sanctions-match"],
    description: "High-confidence sanctions test match requiring human review",
    componentScores: highScores(62),
    explainability: [
      { feature: "sanctions_test_match", impact: 95, direction: "risk_increase", evidence: "Seeded high-confidence sanctions test result; no automatic SAR filing." },
    ],
  }),
];

export const amlRules: AmlRule[] = [
  ["rule-structuring-24h", "Repeated low-value transfers", "structuring", "sum_within_window", "24h", 5, 4500, 23, "review"],
  ["rule-smurfing", "Multiple senders below internal review threshold", "smurfing", "count_within_window", "6h", 4, 2500, 22, "review"],
  ["rule-fan-in", "Many wallets funding one recipient", "fan_in", "count_within_window", "1h", 4, 500, 24, "review"],
  ["rule-fan-out", "One wallet paying many new beneficiaries", "fan_out", "count_within_window", "6h", 4, 700, 24, "review"],
  ["rule-rapid-pass-through", "Cash-in followed by rapid cash-out", "rapid_pass_through", "deviation_from_baseline", "1h", 2, 3000, 26, "hold"],
  ["rule-low-residual-balance", "Low residual balance after incoming funds", "rapid_pass_through", "deviation_from_baseline", "1h", 2, 2500, 20, "review"],
  ["rule-circular-funds", "Circular or returning funds", "circular_funds", "graph_distance_relationship", "24h", 2, 2000, 25, "review"],
  ["rule-threshold-avoidance", "Percentage immediately below internal threshold", "structuring", "percentage_below_threshold", "24h", 4, 4000, 22, "review"],
  ["rule-dormant-reactivation", "Dormant account reactivation", "dormant_reactivation", "deviation_from_baseline", "7d", 5, 5000, 25, "review"],
  ["rule-cross-border", "Unusual cross-border activity", "cross_border", "sum_within_window", "24h", 3, 6000, 18, "review"],
  ["rule-mobile-money-consolidation", "Mobile-money consolidation before cash-out", "mobile_money", "sum_within_window", "6h", 4, 3000, 25, "hold"],
  ["rule-agent-collusion", "Mobile-money agent collusion indicators", "mobile_money", "shared_graph_attribute", "6h", 3, 2500, 24, "review"],
  ["rule-shared-device", "Shared device across unrelated wallets", "mule_account", "shared_graph_attribute", "24h", 3, 1500, 23, "review"],
  ["rule-new-beneficiary", "New beneficiary risk", "beneficiary_risk", "count_within_window", "24h", 1, 1000, 16, "step_up"],
  ["rule-account-testing", "Micro-deposit account testing", "account_testing", "count_within_window", "15m", 3, 10, 22, "review"],
  ["rule-sim-device-change", "SIM or device change before payment", "device_change", "shared_graph_attribute", "1h", 1, 500, 20, "step_up"],
  ["rule-mule-account", "Mule-account indicators", "mule_account", "graph_distance_relationship", "24h", 2, 1500, 26, "escalate"],
  ["rule-ubo-mismatch", "UBO mismatch", "kyb", "not_equal", "30d", 1, 0, 18, "review"],
  ["rule-turnover-mismatch", "Declared turnover mismatch", "kyb", "deviation_from_baseline", "30d", 1, 5000, 20, "review"],
  ["rule-sanctions-match", "Sanctions match", "screening", "equals", "30d", 1, 0, 40, "hold"],
  ["rule-pep-escalation", "PEP escalation", "screening", "equals", "30d", 1, 0, 22, "review"],
  ["rule-source-of-funds", "Source-of-funds concern", "source_of_funds", "equals", "30d", 1, 0, 24, "review"],
].map(([id, name, category, operator, rollingWindow, countThreshold, cumulativeThreshold, scoreContribution, action], index) => ({
  id: String(id),
  name: String(name),
  description: `${name} scenario with configurable internal thresholds and human-review controls.`,
  category: category as AmlRule["category"],
  jurisdiction: "multi-jurisdiction",
  institution: "all",
  customerSegment: "all",
  businessSegment: "all",
  transactionChannel: "all",
  field: category === "kyb" ? "business_profile" : "transaction_cluster",
  operator: operator as AmlRule["operator"],
  comparisonValue: "internal_config",
  aggregation: operator === "graph_distance_relationship" || operator === "shared_graph_attribute" ? "graph" : "sum",
  rollingWindow: rollingWindow as AmlRule["rollingWindow"],
  countThreshold: Number(countThreshold),
  cumulativeThreshold: Number(cumulativeThreshold),
  scoreContribution: Number(scoreContribution),
  priority: Number(scoreContribution) >= 25 ? "critical" : Number(scoreContribution) >= 20 ? "high" : "medium",
  action: action as AmlRule["action"],
  effectiveDate: daysAgo(30),
  owner: index % 3 === 0 ? "rule.admin" : "compliance.ops",
  version: 1,
  approvalStatus: index < 14 ? "approved" : "pending",
  productionStatus: index < 14 ? "active" : "draft",
  logic: {
    join: "AND",
    conditions: [
      { field: "rolling_window", operator: operator as AmlRule["operator"], value: String(rollingWindow) },
      { field: "cumulative_amount", operator: "greater_than", value: String(cumulativeThreshold) },
    ],
  },
  estimatedAlertVolume: 8 + index * 3,
  estimatedFalsePositiveRate: Math.max(4, 18 - index * 0.6),
  performance: { truePositiveRate: 62 + index, falsePositiveRate: Math.max(4, 16 - index * 0.4), lastBacktestedAt: daysAgo(3 + index) },
  versionHistory: [{ version: 1, changedAt: daysAgo(30), changedBy: "rule.admin", reason: "Initial seeded scenario." }],
}));

export const screeningChecks: ScreeningCheck[] = [
  {
    id: "scr-sanctions-fp-777",
    subjectId: "cust-remit-777",
    subjectType: "customer",
    checkType: "sanctions",
    provider: "test-screening-adapter",
    resultStatus: "test_result",
    datasetVersion: "test-list-2026.07",
    checkedAt: ago(90),
    matchScore: 62,
    matchingFields: ["name"],
    disposition: "possible_match",
    reviewer: "compliance.ops",
    evidence: ["Name similarity only; date of birth mismatch. Treat as false-positive candidate pending reviewer disposition."],
    nextReviewDate: daysAgo(-30),
  },
  {
    id: "scr-sanctions-high-901",
    subjectId: "cust-sanction-901",
    subjectType: "customer",
    checkType: "sanctions",
    provider: "test-screening-adapter",
    resultStatus: "test_result",
    datasetVersion: "test-list-2026.07",
    checkedAt: ago(30),
    matchScore: 96,
    matchingFields: ["name", "date_of_birth", "passport"],
    disposition: "true_match",
    reviewer: "mlro.user",
    evidence: ["High-confidence seeded test match. No live provider result claimed."],
    nextReviewDate: daysAgo(1),
  },
  {
    id: "scr-pep-042",
    subjectId: "cust-wallet-042",
    subjectType: "customer",
    checkType: "pep",
    provider: "mock-pep-adapter",
    resultStatus: "mock_result",
    datasetVersion: "mock-pep-2026.07",
    checkedAt: ago(130),
    matchScore: 73,
    matchingFields: ["relative_name"],
    disposition: "needs_review",
    evidence: ["Possible RCA exposure; EDD required."],
    nextReviewDate: daysAgo(12),
  },
  {
    id: "scr-ubo-303",
    subjectId: "bus-dormant-303",
    subjectType: "business",
    checkType: "ubo",
    provider: "manual-kyb-review",
    resultStatus: "manual_verification_required",
    datasetVersion: "manual",
    checkedAt: ago(210),
    matchScore: 0,
    matchingFields: [],
    disposition: "needs_review",
    evidence: ["No identifiable UBO in supplied KYB documents."],
    nextReviewDate: daysAgo(3),
  },
  {
    id: "scr-provider-unavailable",
    subjectId: "bus-agent-909",
    subjectType: "business",
    checkType: "company",
    provider: "company-registry-adapter",
    resultStatus: "provider_unavailable",
    datasetVersion: "unavailable",
    checkedAt: ago(55),
    matchScore: 0,
    matchingFields: [],
    disposition: "needs_review",
    evidence: ["Provider unavailable; manual registry evidence required."],
    nextReviewDate: daysAgo(2),
  },
];

export const seededClusters: MicrotransactionCluster[] = [
  {
    id: "cluster-structuring-001",
    scenario: "structuring",
    title: "Repeated payments below internal review threshold",
    riskLevel: "high",
    riskScore: 78,
    transactionIds: ["txn-struct-1", "txn-struct-2", "txn-struct-3", "txn-struct-4", "txn-struct-5"],
    customerIds: ["cust-wallet-042"],
    businessIds: [],
    deviceIds: ["dev-shared-991"],
    ipAddresses: ["198.51.100.42"],
    rollingWindow: "1h",
    transactionCount: 5,
    cumulativeAmount: 4930,
    averageAmount: 986,
    thresholdAvoidancePct: 100,
    evidence: ["Five near-threshold payments occurred inside 40 minutes.", "Cumulative value exceeded the configured internal review amount."],
    recommendedAction: "Open alert review and request source-of-funds evidence if unexplained.",
    firstSeenAt: ago(40),
    lastSeenAt: ago(20),
  },
  {
    id: "cluster-fanin-001",
    scenario: "fan_in",
    title: "Multiple wallets funding one collector wallet",
    riskLevel: "high",
    riskScore: 74,
    transactionIds: ["txn-fanin-1", "txn-fanin-2", "txn-fanin-3", "txn-fanin-4"],
    customerIds: ["cust-fanin-1", "cust-fanin-2", "cust-fanin-3", "cust-fanin-4"],
    businessIds: [],
    deviceIds: ["dev-shared-991"],
    ipAddresses: ["198.51.100.42"],
    rollingWindow: "6h",
    transactionCount: 4,
    cumulativeAmount: 792,
    averageAmount: 198,
    thresholdAvoidancePct: 100,
    evidence: ["Four wallets fund one recipient.", "Two senders share device and IP context."],
    recommendedAction: "Investigate beneficial ownership and linked device context.",
    firstSeenAt: ago(95),
    lastSeenAt: ago(59),
  },
  {
    id: "cluster-agent-collusion-001",
    scenario: "mobile_money_consolidation",
    title: "Agent-network consolidation and cash-out",
    riskLevel: "critical",
    riskScore: 86,
    transactionIds: ["txn-agent-collusion-001", "txn-pass-through-in", "txn-pass-through-out"],
    customerIds: ["cust-agent-operator", "cust-wallet-042"],
    businessIds: ["bus-agent-909"],
    deviceIds: ["dev-agent-19", "dev-shared-991"],
    ipAddresses: ["198.51.100.119", "198.51.100.42"],
    rollingWindow: "6h",
    transactionCount: 3,
    cumulativeAmount: 9960,
    averageAmount: 3320,
    thresholdAvoidancePct: 33,
    evidence: ["Cash-in followed by rapid cash-out.", "Mobile-money agent wallet and shared handset appear in graph."],
    recommendedAction: "Hold settlement, review agent activity, and consider MLRO escalation.",
    firstSeenAt: ago(73),
    lastSeenAt: ago(32),
  },
];

export const amlAlerts: AmlAlert[] = [
  {
    id: "aml-alert-structuring-001",
    category: "structuring",
    eventId: "evt-cluster-structuring-001",
    subjectId: "cust-wallet-042",
    subjectType: "cluster",
    relatedTransactions: ["txn-struct-1", "txn-struct-2", "txn-struct-3", "txn-struct-4", "txn-struct-5"],
    rulesTriggered: ["rule-structuring-24h", "rule-threshold-avoidance"],
    riskScores: { fraud: 68, aml: 82, unified: 78 },
    cumulativeAmount: 4930,
    transactionCount: 5,
    rollingWindow: "1h",
    explanation: "Repeated low-value payments formed a high-risk structuring cluster inside an internal rolling window.",
    evidence: ["Near-identical amounts", "Shared device", "Cumulative value over configured review amount"],
    suggestedAction: "Assign to AML analyst and request transaction purpose evidence.",
    assignedAnalyst: "amara.okafor",
    status: "assigned",
    serviceLevelDeadline: ago(-240),
    relatedAlerts: [],
    relatedCases: ["aml-case-001"],
    createdAt: ago(38),
    updatedAt: ago(12),
  },
  {
    id: "aml-alert-sanctions-901",
    category: "screening",
    eventId: "txn-sanction-test-001",
    subjectId: "cust-sanction-901",
    subjectType: "customer",
    relatedTransactions: ["txn-sanction-test-001"],
    rulesTriggered: ["rule-sanctions-match"],
    riskScores: { fraud: 70, aml: 95, unified: 88 },
    cumulativeAmount: 6900,
    transactionCount: 1,
    rollingWindow: "30d",
    explanation: "High-confidence sanctions test match requires human review and restricted outbound movement.",
    evidence: ["Test screening match score 96", "Outbound bank transfer attempted"],
    suggestedAction: "Hold and escalate to MLRO-equivalent reviewer.",
    assignedAnalyst: "mlro.user",
    status: "referred_to_mlro",
    serviceLevelDeadline: ago(-60),
    relatedAlerts: [],
    relatedCases: ["aml-case-mlro-901"],
    createdAt: ago(12),
    updatedAt: ago(6),
  },
];

export const investigations: AmlInvestigation[] = [
  {
    id: "aml-case-001",
    alertId: "aml-alert-structuring-001",
    owner: "amara.okafor",
    priority: "high",
    hypothesis: "Wallet activity may represent threshold avoidance and rapid beneficiary testing.",
    status: "open",
    linkedEntities: ["cust-wallet-042", "wallet-042", "dev-shared-991", "acct-struct-beneficiary"],
    linkedTransactions: ["txn-struct-1", "txn-struct-2", "txn-struct-3", "txn-struct-4", "txn-struct-5"],
    sourceOfFundsAnalysis: "Declared market proceeds do not yet fully explain clustered activity.",
    sourceOfWealthAnalysis: "Wealth profile is small-business income; EDD evidence requested.",
    customerExplanation: "Customer states payments are supplier settlement instalments.",
    findings: ["Five payments clustered below internal review threshold.", "Shared device context requires review."],
    recommendedAction: "Request supplier invoices and keep new beneficiaries in manual review.",
    evidenceExportReady: true,
    timeline: [
      { at: ago(38), actor: "aml-detector", action: "alert_created", detail: "Structuring cluster generated alert." },
      { at: ago(20), actor: "amara.okafor", action: "evidence_requested", detail: "Requested supplier invoices and source-of-funds evidence." },
    ],
    evidence: [
      { id: "ev-struct-1", type: "rolling_window", label: "Five near-threshold transactions in 40 minutes", confidence: 88 },
      { id: "ev-struct-2", type: "graph", label: "Shared device with unrelated wallets", confidence: 76 },
    ],
    auditHistory: [],
  },
  {
    id: "aml-case-mlro-901",
    alertId: "aml-alert-sanctions-901",
    owner: "mlro.user",
    priority: "critical",
    hypothesis: "High-confidence sanctions test match and attempted outbound transfer require nominated-officer review.",
    status: "mlro_review",
    linkedEntities: ["cust-sanction-901", "acct-sanction-901", "counterparty-screening-hit"],
    linkedTransactions: ["txn-sanction-test-001"],
    sourceOfFundsAnalysis: "Consulting invoices require independent validation.",
    sourceOfWealthAnalysis: "Accumulated incoming value exceeds declared source-of-wealth evidence.",
    findings: ["High-confidence test screening match.", "Outbound transfer held pending disposition."],
    recommendedAction: "Maintain hold and complete MLRO review. Do not submit SAR automatically.",
    mlroDecision: "pending",
    evidenceExportReady: true,
    timeline: [
      { at: ago(12), actor: "screening-adapter", action: "match_created", detail: "High-confidence seeded sanctions match." },
      { at: ago(6), actor: "system", action: "referred_to_mlro", detail: "Alert referred for nominated-officer review." },
    ],
    evidence: [
      { id: "ev-sanction-1", type: "screening", label: "High-confidence sanctions test match", confidence: 96 },
      { id: "ev-sanction-2", type: "transaction", label: "Held outbound transfer", confidence: 91 },
    ],
    auditHistory: [],
  },
];

export const sarDrafts: SarDraft[] = [
  {
    id: "sar-draft-901",
    caseId: "aml-case-mlro-901",
    subjectIds: ["cust-sanction-901"],
    businessIds: [],
    accountIds: ["acct-sanction-901"],
    walletIds: [],
    transactionChronology: ["txn-sanction-test-001 attempted outbound transfer and was held."],
    totalSuspiciousValue: 6900,
    suspicionIndicators: ["High-confidence seeded sanctions test match", "Source-of-wealth gap", "Outbound transfer attempt"],
    reasonForSuspicion: "Decision Intelligence draft: the available evidence indicates a possible sanctions-related suspicious activity pattern requiring human validation.",
    paymentCorridors: ["ZA-KE"],
    sourceOfFundsConcerns: ["Consulting invoices have not independently validated observed activity."],
    relatedEntities: ["counterparty-screening-hit"],
    supportingEvidence: ["scr-sanctions-high-901", "txn-sanction-test-001", "aml-case-mlro-901"],
    internalReferences: ["aml-alert-sanctions-901"],
    glossaryCategories: ["sanctions", "source of funds", "cross-border transfer"],
    investigator: "mlro.user",
    mlroReviewStatus: "ready_for_review",
    narrative:
      "Decision Intelligence draft requiring human validation. Seeded test screening produced a high-confidence sanctions match for cust-sanction-901, followed by an attempted outbound transfer. The transfer was held and the matter requires nominated-officer review.",
    aiGenerated: true,
    tippingOffControls: ["No customer-facing note", "Restricted export", "Versioned edits after approval", "Manual submission only"],
    version: 1,
    createdAt: ago(8),
    updatedAt: ago(4),
  },
];

export const relationshipGraph: { nodes: GraphNode[]; edges: GraphEdge[] } = {
  nodes: [
    { id: "cust-wallet-042", type: "user", label: "KYC customer 042", risk: 71, x: 24, y: 42 },
    { id: "wallet-042", type: "wallet", label: "Wallet 042", risk: 77, x: 44, y: 42 },
    { id: "dev-shared-991", type: "device", label: "Shared handset", risk: 82, x: 64, y: 28 },
    { id: "acct-struct-beneficiary", type: "beneficiary", label: "Beneficiary cluster", risk: 78, x: 72, y: 52 },
    { id: "bus-agent-909", type: "business", label: "Moyo Cash", risk: 67, x: 44, y: 72 },
    { id: "wallet-agent-19", type: "wallet", label: "Agent wallet 19", risk: 79, x: 68, y: 78 },
  ],
  edges: [
    { id: "aml-edge-1", source: "cust-wallet-042", target: "wallet-042", relationship: "owns", weight: 0.88 },
    { id: "aml-edge-2", source: "wallet-042", target: "dev-shared-991", relationship: "used_on", weight: 0.76 },
    { id: "aml-edge-3", source: "wallet-042", target: "acct-struct-beneficiary", relationship: "paid_to", weight: 0.82 },
    { id: "aml-edge-4", source: "bus-agent-909", target: "wallet-agent-19", relationship: "owns", weight: 0.84 },
    { id: "aml-edge-5", source: "wallet-agent-19", target: "dev-shared-991", relationship: "shares_device", weight: 0.62 },
  ],
};

export const amlAudit: AuditEvent[] = [
  {
    id: "aud-aml-seed-1",
    actor: "system",
    role: "admin",
    action: "aml.seed.loaded",
    target: "aml-workspace",
    metadata: { reason: "Seeded fictional AML/KYC/KYB monitoring scenarios." },
    createdAt: ago(180),
  },
];

export const scenarioCoverage = [
  "Normal salary and household payments",
  "Normal mobile-money use",
  "Repeated microtransactions below an internal threshold",
  "Multiple wallets funding one account",
  "One account distributing funds to many new beneficiaries",
  "Cash-in followed by rapid cash-out",
  "Wallet-to-bank pass-through",
  "Cross-border remittance structuring",
  "Dormant wallet reactivation",
  "SIM or device change followed by unusual payments",
  "Mobile-money agent collusion indicators",
  "Business turnover mismatch",
  "Complex business ownership",
  "Sanctions false-positive match",
  "High-confidence sanctions match",
  "PEP requiring enhanced due diligence",
  "Alert converted into an investigation",
  "Case prepared for MLRO review",
  "SAR draft awaiting approval",
  "False positive used as model feedback",
];
