import { OperatingPicture } from "./types";

const iso = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60_000).toISOString();

export const fallbackPicture: OperatingPicture = {
  metrics: {
    fraudDetectionRate: 93.4,
    falsePositiveReduction: 28.6,
    recoveryRate: 71.8,
    decisionLatencyMs: 146,
    analystEfficiencyGain: 41.2,
    eventsPerMinute: 18342,
    blockedValue: 4320000,
    recalledValue: 1180000,
  },
  alerts: [
    {
      id: "alt-9012",
      eventId: "evt-9012",
      title: "High-risk beneficiary added before transfer",
      severity: "critical",
      institution: "AfriBank",
      amount: 186000,
      currency: "USD",
      subjectHash: "usr_93f6a2c8",
      decision: "block",
      reasons: ["new beneficiary", "consortium mule match", "velocity anomaly"],
      location: { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792 },
      createdAt: iso(3),
    },
    {
      id: "alt-8841",
      eventId: "evt-8841",
      title: "Geo-velocity login followed by account update",
      severity: "high",
      institution: "KoraPay",
      amount: 42000,
      currency: "USD",
      subjectHash: "usr_aa19de09",
      decision: "review",
      reasons: ["impossible travel", "new device", "email intelligence risk"],
      location: { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219 },
      createdAt: iso(8),
    },
  ],
  payments: [
    {
      id: "pay-8GPI-4419",
      amount: 186000,
      currency: "USD",
      origin: "AfriBank NG",
      destination: "Baltic Correspondent LV",
      status: "flagged",
      recallAvailable: true,
      delayAnomaly: 87,
      route: [
        { institution: "AfriBank NG", country: "NG", status: "initiated", timestamp: iso(11), risk: 64 },
        { institution: "Pan-African Switch", country: "GH", status: "held", timestamp: iso(7), risk: 79 },
        { institution: "Baltic Correspondent", country: "LV", status: "flagged", timestamp: iso(4), risk: 91 },
      ],
      riskSignals: ["new beneficiary", "cross-border route", "known mule IBAN"],
      updatedAt: iso(4),
    },
  ],
  cases: [
    {
      id: "case-2048",
      title: "Suspected mule network funding round",
      status: "investigating",
      priority: "critical",
      assignee: "Amara Okafor",
      institution: "AfriBank",
      alertId: "alt-9012",
      lossExposure: 186000,
      recoveryPotential: 142000,
      entities: ["usr_93f6a2c8", "dev_a4fd", "acct_0041", "pay-8GPI-4419"],
      timeline: [
        {
          at: iso(21),
          actor: "fraud-engine-service",
          action: "risk_score",
          detail: "Transaction scored 92/100 with block decision.",
        },
        {
          at: iso(7),
          actor: "payment-tracking-service",
          action: "hold_payment",
          detail: "Payment held at Pan-African Switch with recall still available.",
        },
      ],
      evidence: [
        { id: "ev-graph-1", type: "identity_graph", label: "Shared device across mule cluster", confidence: 96 },
        { id: "ev-pay-1", type: "payment_route", label: "Known laundering route", confidence: 88 },
      ],
      nextActions: [
        "Issue payment recall before correspondent settlement closes.",
        "Request encrypted consortium corroboration for beneficiary hash.",
        "Escalate SAR draft to compliance officer.",
      ],
      sarDraft: "Subject initiated a high-value cross-border transfer after adding a beneficiary with consortium mule indicators.",
      updatedAt: iso(5),
    },
  ],
  institutions: [
    { id: "inst-afb", name: "AfriBank", country: "NG", trustScore: 94, reputation: 91, sharedAlerts: 1874, confirmedFraudRate: 74, encryptedKeyId: "vault://keys/consortium/afb" },
    { id: "inst-kora", name: "KoraPay", country: "KE", trustScore: 89, reputation: 86, sharedAlerts: 1392, confirmedFraudRate: 69, encryptedKeyId: "vault://keys/consortium/kora" },
    { id: "inst-safa", name: "Safra Mutual", country: "ZA", trustScore: 92, reputation: 88, sharedAlerts: 1178, confirmedFraudRate: 72, encryptedKeyId: "vault://keys/consortium/safa" },
  ],
  typologies: [
    { id: "typ-mule-burst", name: "Mule account burst funding", severity: "critical", prevalence: 78, sharedBy: 17, indicators: ["new beneficiary", "rapid transfer chain", "shared device"] },
    { id: "typ-ato-geo", name: "ATO with geo-velocity pivot", severity: "high", prevalence: 62, sharedBy: 12, indicators: ["impossible travel", "new device", "failed step-up"] },
  ],
  heatmap: [
    { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792, risk: 91, alerts: 284 },
    { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219, risk: 78, alerts: 166 },
    { city: "Johannesburg", country: "ZA", lat: -26.2041, lng: 28.0473, risk: 72, alerts: 149 },
    { city: "Accra", country: "GH", lat: 5.6037, lng: -0.187, risk: 64, alerts: 98 },
  ],
  graph: {
    nodes: [
      { id: "usr_93f6a2c8", type: "user", label: "User hash", risk: 92, x: 52, y: 50 },
      { id: "dev_a4fd", type: "device", label: "Device A4FD", risk: 88, x: 35, y: 34 },
      { id: "acct_0041", type: "account", label: "Account 0041", risk: 81, x: 66, y: 35 },
      { id: "pay-8GPI-4419", type: "transaction", label: "Payment 4419", risk: 91, x: 78, y: 55 },
      { id: "ip_198_51_100_24", type: "ip", label: "IP hash", risk: 73, x: 24, y: 62 },
    ],
    edges: [
      { id: "edge-1", source: "usr_93f6a2c8", target: "dev_a4fd", relationship: "used_on", weight: 0.92 },
      { id: "edge-2", source: "usr_93f6a2c8", target: "acct_0041", relationship: "owns", weight: 0.88 },
      { id: "edge-3", source: "acct_0041", target: "pay-8GPI-4419", relationship: "transferred_to", weight: 0.95 },
      { id: "edge-4", source: "dev_a4fd", target: "ip_198_51_100_24", relationship: "linked_to", weight: 0.74 },
    ],
  },
  riskDistribution: [
    { level: "low", count: 13284, color: "#22c55e" },
    { level: "medium", count: 3842, color: "#f59e0b" },
    { level: "high", count: 1127, color: "#fb7185" },
    { level: "critical", count: 219, color: "#a855f7" },
  ],
  amlCustomers: [
    { customerId: "cust-9041", name: "Corporate remitter hash", fraudRisk: 91, amlRisk: 82, sanctionsRisk: 37, unifiedRisk: 86, riskLevel: "critical", drivers: ["layering route", "mule beneficiary", "high value burst"] },
    { customerId: "cust-2290", name: "Retail wallet hash", fraudRisk: 77, amlRisk: 53, sanctionsRisk: 12, unifiedRisk: 68, riskLevel: "high", drivers: ["ATO indicators", "new device", "rapid beneficiary update"] },
  ],
  learning: {
    modelVersion: "hybrid-risk-2026.07",
    lastRetrainedAt: iso(1560),
    driftIndex: 0.17,
    labelledCases: 12842,
    falsePositiveRate: 7.8,
    precisionLift: 18.4,
    feedbackQueue: 37,
  },
  audit: [
    { id: "aud-1", actor: "amara.okafor", role: "fraud_investigator", action: "payment.recall.requested", target: "pay-8GPI-4419", metadata: { encrypted: true }, createdAt: iso(6) },
  ],
  agenticOperations: {
    agents: [
      {
        id: "agent-data-analyst",
        name: "Data Analyst Agent",
        category: "data_analysis",
        status: "ready",
        automationRate: 86,
        avgRuntimeSeconds: 34,
        humanReviewRequired: false,
        description: "Runs natural-language investigations across transactions, sessions, merchants, devices, disputes, and cases.",
        examplePrompts: ["Identify merchants with a high concentration of shared users."],
        lastRunAt: iso(12),
      },
      {
        id: "agent-graph-analyst",
        name: "Graph Analyst Agent",
        category: "fraud_ring_detection",
        status: "ready",
        automationRate: 79,
        avgRuntimeSeconds: 41,
        humanReviewRequired: true,
        description: "Maps users, devices, IPs, emails, merchants, accounts, and payments to surface fraud rings.",
        examplePrompts: ["Show the top 10 device IDs shared by users."],
        lastRunAt: iso(18),
      },
      {
        id: "agent-rule-assistant",
        name: "Rule Assistant Agent",
        category: "rule_optimization",
        status: "ready",
        automationRate: 91,
        avgRuntimeSeconds: 26,
        humanReviewRequired: true,
        description: "Turns plain-language hypotheses into testable monitoring rules.",
        examplePrompts: ["Suggest a rule for merchants under 90 days old with no acquiring transactions."],
        lastRunAt: iso(9),
      },
    ],
    recentRuns: [
      {
        id: "run-merchant-collusion",
        agentId: "agent-graph-analyst",
        prompt: "Identify merchants with shared users and collusion links.",
        status: "needs_review",
        confidence: 91,
        completedAt: iso(8),
        summary: "Four merchants show concentrated shared users, common device infrastructure, and dormant-to-spike behavior.",
        findings: ["Velo Digital Goods and Luno Arcade share 244 users.", "Atlas Voucher Hub is under 90 days old with no acquiring transactions."],
        recommendedActions: ["Open merchant EDD.", "Deploy reused-device merchant rule in monitor mode."],
        executionPlan: [
          { id: "resolve-entities", name: "Resolve shared users, merchants, devices, and IPs", status: "completed", evidenceRef: "identity-graph" },
          { id: "rank-links", name: "Rank network links by risk propagation", status: "completed", evidenceRef: "graph-risk" },
          { id: "containment", name: "Queue containment or intelligence sharing action", status: "waiting_approval", evidenceRef: "consortium-package" },
        ],
        actionsQueued: ["act-share-merchant-003"],
        policyDecision: {
          autonomyMode: "monitored",
          allowedToExecute: false,
          approvalRequired: true,
          reason: "Human approval required by Real-time fraud defense: mode monitored, risk 91, value 0.",
        },
      },
    ],
    controlPlane: {
      autonomyMode: "monitored",
      policies: [
        {
          id: "policy-real-time-fraud-defense",
          name: "Real-time fraud defense",
          autonomyMode: "monitored",
          riskThreshold: 72,
          humanApprovalAboveRisk: 88,
          maxAutonomousValue: 25000,
          allowedActions: ["step_up", "hold_payment", "create_case", "propose_rule"],
          escalationRoles: ["fraud_investigator", "admin"],
          description: "Agents can step up or hold moderate-risk activity, while critical or high-value actions require approval.",
        },
      ],
      telemetry: {
        signalsMonitoredDaily: 82400000,
        lastCycleAt: iso(4),
        p95LatencyMs: 142,
        agentPrecision: 92.4,
        falsePositiveReduction: 41.8,
        driftScore: 0.11,
        queuedActions: 3,
        autonomousActionsToday: 127,
        humanApprovalsPending: 2,
        casesCreatedToday: 18,
        paymentValueHeld: 1840000,
        rulesProposedToday: 5,
      },
      emergingPatterns: [
        {
          id: "pattern-remote-access-scam",
          name: "Remote access scam sessions before high-value transfer",
          severity: "critical",
          riskScore: 94,
          signals: ["remote_access_tool", "new beneficiary", "behaviour deviation", "high-value transfer"],
          affectedEntities: ["usr_93f6a2c8", "acct_0041", "pay-8GPI-4419"],
          proposedRuleId: "rule-remote-access-transfer-hold",
          firstSeenAt: iso(47),
          lastSeenAt: iso(4),
          impactEstimate: "$1.84M payments held before settlement",
          status: "contained",
        },
        {
          id: "pattern-agentic-browser-card-testing",
          name: "Agentic browser automation card testing",
          severity: "high",
          riskScore: 86,
          signals: ["bot_score", "low-value probes", "device fingerprint reuse", "merchant hopping"],
          affectedEntities: ["mrc-velo-184", "mrc-luno-092", "dev-shared-019"],
          proposedRuleId: "rule-agentic-browser-card-testing",
          firstSeenAt: iso(136),
          lastSeenAt: iso(12),
          impactEstimate: "3,900 low-value probes suppressed",
          status: "watching",
        },
      ],
      actionQueue: [
        {
          id: "act-rule-card-testing-002",
          agentId: "agent-rule-assistant",
          type: "propose_rule",
          title: "Deploy agentic browser card-testing rule",
          description: "Add a monitor-mode rule for low-value probes, high bot score, and fingerprint reuse across merchants.",
          riskScore: 86,
          status: "requires_approval",
          requiresApproval: true,
          evidence: ["pattern-agentic-browser-card-testing", "rule-agentic-browser-card-testing"],
          createdAt: iso(12),
        },
        {
          id: "act-share-merchant-003",
          agentId: "agent-graph-analyst",
          type: "share_intelligence",
          title: "Share anonymised merchant collusion package",
          description: "Publish HMAC-only collusion package to trusted institutions.",
          riskScore: 91,
          status: "requires_approval",
          requiresApproval: true,
          evidence: ["mrc-velo-184", "mrc-luno-092", "dev-shared-019"],
          createdAt: iso(17),
        },
      ],
    },
    deploymentReadiness: {
      environment: "development",
      status: "warn",
      generatedAt: iso(1),
      checks: [
        { id: "readiness-api", name: "API health and rate limiting", status: "pass", detail: "Health, RBAC, Helmet, CORS, and throttling are enabled." },
        { id: "readiness-secrets", name: "Production secret binding", status: "warn", detail: "Local development secret is in use.", remediation: "Mount production secrets from a vault before launch." },
        { id: "readiness-agentops", name: "AgentOps governance", status: "pass", detail: "Autonomy modes, approval queues, policy thresholds, telemetry, and audit trails are modeled." },
      ],
    },
    merchantInsights: [
      {
        merchantId: "mrc-velo-184",
        merchantName: "Velo Digital Goods",
        ageDays: 42,
        sharedUsers: 318,
        linkedMerchants: ["Luno Arcade", "Atlas Voucher Hub"],
        dormantDays: 64,
        sessionSpikePct: 870,
        noAcquiringTransactions: true,
        deviceReuseCount: 23,
        collusionScore: 91,
        riskLevel: "critical",
        findings: ["High overlap of user hashes with linked merchants.", "Dormant for 64 days before session spike."],
      },
      {
        merchantId: "mrc-luno-092",
        merchantName: "Luno Arcade",
        ageDays: 76,
        sharedUsers: 244,
        linkedMerchants: ["Velo Digital Goods"],
        dormantDays: 61,
        sessionSpikePct: 640,
        noAcquiringTransactions: false,
        deviceReuseCount: 17,
        collusionScore: 84,
        riskLevel: "critical",
        findings: ["Shared users moved from low-value card tests to high-value digital purchases."],
      },
    ],
    sharedDevices: [
      {
        deviceId: "dev-fp-88a1",
        sharedUsers: 47,
        locations: [
          { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792, users: 22 },
          { city: "Accra", country: "GH", lat: 5.6037, lng: -0.187, users: 14 },
        ],
        sessionRiskSignals: ["residential proxy", "copy-paste in card fields", "timezone mismatch"],
        linkedMerchants: ["Velo Digital Goods", "Luno Arcade"],
        riskScore: 94,
      },
    ],
    accountTakeovers: [
      {
        userId: "usr_aa19de09",
        accountId: "acct-7782",
        riskScore: 92,
        last30DaySignals: ["new device", "impossible travel", "password reset", "beneficiary update"],
        firstSeenDevice: "dev-trusted-1102",
        currentDevice: "dev-fp-88a1",
        geographyShift: "Nairobi to Lagos in 43 minutes",
        recommendedAction: "Freeze outbound movement and require assisted identity reverification.",
      },
    ],
    osintFindings: [
      {
        entityName: "Velo Digital Goods",
        riskLevel: "high",
        sourcesChecked: ["business registry", "domain WHOIS", "adverse media", "social web"],
        findings: ["Domain registration changed 9 days before spike.", "Declared category conflicts with observed voucher resale content."],
        adverseMediaSignals: ["complaint forum references to non-delivery"],
        ownershipSignals: ["operator email hash appears on Atlas Voucher Hub"],
        recommendedAction: "Open EDD review and restrict settlement until review completes.",
        completedAt: iso(18),
      },
    ],
    disputes: [
      {
        disputeId: "disp-visa-3001",
        cardNetwork: "Visa",
        reasonCode: "10.4",
        qualifiesForVisaCE30: true,
        confidence: 91,
        customerId: "cust-2290",
        merchantName: "Velo Digital Goods",
        disputedTransaction: { id: "txn-disputed-9901", amount: 460, occurredAt: iso(5760) },
        compellingTransactions: [
          { id: "txn-ce3-1101", amount: 89, occurredAt: iso(138240), deviceId: "dev-fp-88a1", ipAddress: "198.51.100.24", shippingAddressMatch: true, accountLoginMatch: true },
          { id: "txn-ce3-1102", amount: 112, occurredAt: iso(105120), deviceId: "dev-fp-88a1", ipAddress: "198.51.100.24", shippingAddressMatch: true, accountLoginMatch: true },
          { id: "txn-ce3-1103", amount: 134, occurredAt: iso(59040), deviceId: "dev-fp-88a1", ipAddress: "198.51.100.24", shippingAddressMatch: true, accountLoginMatch: true },
        ],
        evidenceSummary: "Three prior undisputed transactions match account login, device, IP, and shipping evidence.",
      },
    ],
    lowHighPatterns: [
      { userId: "usr_93f6a2c8", lowValueMerchant: "Northstar Skins", highValueMerchant: "Velo Digital Goods", lowValueAmount: 2.1, highValueAmount: 620, elapsedHours: 4, riskScore: 88 },
    ],
    suggestedRules: [
      {
        id: "rule-new-merchant-reused-device",
        name: "New merchant with reused operator device",
        description: "Review merchants under 90 days old, with no acquiring transactions, when their device has been used by more than five accounts.",
        logic: "merchant.age_days < 90 AND merchant.acquiring_txn_count = 0 AND device.distinct_account_count > 5",
        expectedFireRate: 1.8,
        expectedFalsePositiveReduction: 22,
        action: "review",
        backtestSummary: "Backtest found 42 merchant events, 31 confirmed risky, and avoided broad review of 1,690 low-risk merchants.",
      },
    ],
    workforceImpact: {
      manualHoursSavedMonthly: 1280,
      alertsAutoResolvedPct: 74,
      falsePositiveQueueClearedPct: 68,
      estimatedFteRedeployable: 7.4,
      monthlyCostAvoidance: 214000,
      redeploymentRecommendations: ["Move L1 reviewers into complex investigations and merchant EDD.", "Shift capacity into model governance and reporting quality control."],
      technicalFocusAreas: ["Payment interdiction tuning", "Fraud ring disruption playbooks", "Model drift reviews"],
    },
    demoVideo: {
      id: "demo-agentic-ops",
      title: "African Guard Agentic Fraud Ops Walkthrough",
      durationSeconds: 390,
      src: "/demo/african-guard-agentic-ops-demo.mp4",
      poster: "/demo/agentic-ops-poster.svg",
      chapters: [
        { id: "demo-1", title: "Command center orientation", timestampSeconds: 0, narration: "Start with live risk, automation, losses prevented, and capacity saved.", focusArea: "Operating console" },
        { id: "demo-2", title: "Run analyst agents", timestampSeconds: 54, narration: "Use Data, Graph, OSINT, Dispute, and Rule Assistant agents.", focusArea: "Agentic workflows" },
        { id: "demo-3", title: "Train teams", timestampSeconds: 292, narration: "Launch guided paths or request facilitated training.", focusArea: "Training academy" },
      ],
      transcript: ["African Guard reduces manual review volume with governed AI agents.", "Every recommendation keeps evidence, confidence, and human review controls attached."],
    },
    learningPaths: [
      {
        id: "path-fraud-ops",
        title: "Agentic Fraud Ops Certification",
        subscriberTier: "core",
        completionPct: 42,
        certification: "African Guard Certified Fraud Operator",
        lessons: [
          { id: "lesson-agent-basics", title: "Run safe agent investigations", durationMinutes: 18, role: "analyst", status: "completed", objectives: ["Choose the right agent", "Read confidence and evidence"], simulationPrompt: "Review activity from the last 30 days and identify ATO cases." },
          { id: "lesson-merchant-risk", title: "Detect merchant collusion", durationMinutes: 24, role: "fraud_investigator", status: "in_progress", objectives: ["Interpret shared-user concentration", "Validate linked merchants"], simulationPrompt: "Identify dormant merchants with session spikes." },
        ],
      },
    ],
    facilitatedTraining: [
      { id: "train-remote", title: "Remote analyst onboarding workshop", format: "remote", duration: "2 half-days", audience: "Analysts and team leads", outcomes: ["Operational readiness", "Agent prompting playbooks"], includesSandbox: true },
      { id: "train-onsite", title: "Onsite fraud and AML transformation sprint", format: "onsite", duration: "3 days", audience: "Fraud, compliance, product risk, and engineering leadership", outcomes: ["Workflow redesign", "Capacity redeployment plan"], includesSandbox: true },
    ],
  },
};
