import {
  AgentCapability,
  AgentOpsControlPlane,
  AgentRunResult,
  Alert,
  AmlCustomerRisk,
  AuditEvent,
  ComplianceGovernance,
  DemoVideo,
  DeploymentReadiness,
  DeveloperApiKey,
  EnterprisePlatform,
  EvidenceCapture,
  DisputeEvidence,
  FacilitatedTrainingOffer,
  FraudTypology,
  GraphEdge,
  GraphNode,
  HeatmapPoint,
  Institution,
  IntegrationConnection,
  InvestigationCase,
  LearningState,
  LearningPath,
  LowHighPattern,
  MerchantRiskInsight,
  OperatingMetrics,
  OsintInvestigationResult,
  OsintFinding,
  PaymentNetworkAdapter,
  Payment,
  SharedDeviceInsight,
  SuggestedRule,
  TenantOrganisation,
  TransactionMonitoringRecord,
  UserAccessProfile,
  WorkforceImpact,
  AccountTakeoverInsight,
} from "./domain";

const now = new Date();
const minutesAgo = (minutes: number) =>
  new Date(now.getTime() - minutes * 60_000).toISOString();

export const institutions: Institution[] = [
  {
    id: "inst-afb",
    name: "AfriBank",
    country: "NG",
    trustScore: 94,
    reputation: 91,
    sharedAlerts: 1874,
    confirmedFraudRate: 74,
    encryptedKeyId: "vault://keys/consortium/afb",
  },
  {
    id: "inst-kora",
    name: "KoraPay",
    country: "KE",
    trustScore: 89,
    reputation: 86,
    sharedAlerts: 1392,
    confirmedFraudRate: 69,
    encryptedKeyId: "vault://keys/consortium/kora",
  },
  {
    id: "inst-safa",
    name: "Safra Mutual",
    country: "ZA",
    trustScore: 92,
    reputation: 88,
    sharedAlerts: 1178,
    confirmedFraudRate: 72,
    encryptedKeyId: "vault://keys/consortium/safa",
  },
  {
    id: "inst-cedi",
    name: "CediTrust",
    country: "GH",
    trustScore: 84,
    reputation: 82,
    sharedAlerts: 904,
    confirmedFraudRate: 63,
    encryptedKeyId: "vault://keys/consortium/cedi",
  },
];

export const alerts: Alert[] = [
  {
    id: "alt-9012",
    eventId: "evt-9012",
    title: "High-risk beneficiary added before transfer",
    severity: "critical",
    institution: "AfriBank",
    amount: 186000,
    currency: "USD",
    subjectHash: "usr_93f6a2c8",
    decision: "block",
    reasons: ["new beneficiary", "consortium mule match", "velocity anomaly"],
    location: { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792 },
    createdAt: minutesAgo(3),
  },
  {
    id: "alt-8841",
    eventId: "evt-8841",
    title: "Geo-velocity login followed by account update",
    severity: "high",
    institution: "KoraPay",
    amount: 42000,
    currency: "USD",
    subjectHash: "usr_aa19de09",
    decision: "review",
    reasons: ["impossible travel", "new device", "email intelligence risk"],
    location: { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219 },
    createdAt: minutesAgo(8),
  },
  {
    id: "alt-8727",
    eventId: "evt-8727",
    title: "Merchant refund laundering pattern",
    severity: "high",
    institution: "Safra Mutual",
    amount: 78500,
    currency: "USD",
    subjectHash: "mrc_19db7e41",
    decision: "review",
    reasons: ["refund loop", "linked merchant cluster", "AML typology match"],
    location: { city: "Johannesburg", country: "ZA", lat: -26.2041, lng: 28.0473 },
    createdAt: minutesAgo(14),
  },
];

export const payments: Payment[] = [
  {
    id: "pay-8GPI-4419",
    amount: 186000,
    currency: "USD",
    origin: "AfriBank NG",
    destination: "Baltic Correspondent LV",
    status: "flagged",
    recallAvailable: true,
    delayAnomaly: 87,
    route: [
      {
        institution: "AfriBank NG",
        country: "NG",
        status: "initiated",
        timestamp: minutesAgo(11),
        risk: 64,
      },
      {
        institution: "Pan-African Switch",
        country: "GH",
        status: "held",
        timestamp: minutesAgo(7),
        risk: 79,
      },
      {
        institution: "Baltic Correspondent",
        country: "LV",
        status: "flagged",
        timestamp: minutesAgo(4),
        risk: 91,
      },
    ],
    riskSignals: ["new beneficiary", "cross-border route", "known mule IBAN"],
    updatedAt: minutesAgo(4),
  },
  {
    id: "pay-8GPI-4420",
    amount: 32500,
    currency: "USD",
    origin: "KoraPay KE",
    destination: "Gulf Exchange AE",
    status: "in_flight",
    recallAvailable: true,
    delayAnomaly: 46,
    route: [
      {
        institution: "KoraPay KE",
        country: "KE",
        status: "initiated",
        timestamp: minutesAgo(17),
        risk: 31,
      },
      {
        institution: "Regional Settlement Hub",
        country: "RW",
        status: "in_flight",
        timestamp: minutesAgo(9),
        risk: 43,
      },
    ],
    riskSignals: ["unusual payment hour", "device change within 1h"],
    updatedAt: minutesAgo(9),
  },
];

export const cases: InvestigationCase[] = [
  {
    id: "case-2048",
    title: "Suspected mule network funding round",
    status: "investigating",
    priority: "critical",
    assignee: "Amara Okafor",
    institution: "AfriBank",
    alertId: "alt-9012",
    lossExposure: 186000,
    recoveryPotential: 142000,
    entities: ["usr_93f6a2c8", "dev_a4fd", "acct_0041", "pay-8GPI-4419"],
    timeline: [
      {
        at: minutesAgo(21),
        actor: "fraud-engine-service",
        action: "risk_score",
        detail: "Transaction scored 92/100 with block decision.",
      },
      {
        at: minutesAgo(18),
        actor: "identity-graph-service",
        action: "link_analysis",
        detail: "Device linked to three prior mule accounts across two institutions.",
      },
      {
        at: minutesAgo(7),
        actor: "payment-tracking-service",
        action: "hold_payment",
        detail: "Payment held at Pan-African Switch with recall still available.",
      },
    ],
    evidence: [
      {
        id: "ev-graph-1",
        type: "identity_graph",
        label: "Shared device across mule cluster",
        confidence: 96,
      },
      {
        id: "ev-pay-1",
        type: "payment_route",
        label: "Correspondent leg matched known laundering route",
        confidence: 88,
      },
    ],
    nextActions: [
      "Issue payment recall before correspondent settlement closes.",
      "Request encrypted consortium corroboration for beneficiary hash.",
      "Escalate SAR draft to compliance officer.",
    ],
    sarDraft:
      "Subject initiated a high-value cross-border transfer shortly after adding a beneficiary with consortium mule indicators. Device and account graph analysis links the subject to multiple suspicious accounts.",
    updatedAt: minutesAgo(5),
  },
  {
    id: "case-2051",
    title: "Account takeover after impossible-travel login",
    status: "escalated",
    priority: "high",
    assignee: "Thabo Mbeki",
    institution: "KoraPay",
    alertId: "alt-8841",
    lossExposure: 42000,
    recoveryPotential: 39000,
    entities: ["usr_aa19de09", "ip_198_51_100_24", "dev_93ad"],
    timeline: [
      {
        at: minutesAgo(35),
        actor: "alert-stream-service",
        action: "alert",
        detail: "New-device login followed by beneficiary update.",
      },
      {
        at: minutesAgo(19),
        actor: "case-management-service",
        action: "escalate",
        detail: "Escalated after second failed step-up challenge.",
      },
    ],
    evidence: [
      {
        id: "ev-id-9",
        type: "digital_identity",
        label: "IP reputation and email age mismatch",
        confidence: 84,
      },
    ],
    nextActions: [
      "Freeze outbound transfers pending customer verification.",
      "Compare device hash against consortium alert feed.",
    ],
    sarDraft:
      "Account activity indicates likely account takeover based on impossible travel, new-device behavior, and failed authentication challenges.",
    updatedAt: minutesAgo(13),
  },
];

export const graphNodes: GraphNode[] = [
  { id: "usr_93f6a2c8", type: "user", label: "User hash", risk: 92, x: 52, y: 50 },
  { id: "dev_a4fd", type: "device", label: "Device A4FD", risk: 88, x: 35, y: 34 },
  { id: "acct_0041", type: "account", label: "Account 0041", risk: 81, x: 66, y: 35 },
  { id: "pay-8GPI-4419", type: "transaction", label: "Payment 4419", risk: 91, x: 78, y: 55 },
  { id: "mrc_19db7e41", type: "merchant", label: "Merchant cluster", risk: 76, x: 59, y: 74 },
  { id: "ip_198_51_100_24", type: "ip", label: "IP hash", risk: 73, x: 24, y: 62 },
  { id: "email_39da", type: "email", label: "Email hash", risk: 67, x: 42, y: 78 },
];

export const graphEdges: GraphEdge[] = [
  { id: "edge-1", source: "usr_93f6a2c8", target: "dev_a4fd", relationship: "used_on", weight: 0.92 },
  { id: "edge-2", source: "usr_93f6a2c8", target: "acct_0041", relationship: "owns", weight: 0.88 },
  { id: "edge-3", source: "acct_0041", target: "pay-8GPI-4419", relationship: "transferred_to", weight: 0.95 },
  { id: "edge-4", source: "dev_a4fd", target: "ip_198_51_100_24", relationship: "linked_to", weight: 0.74 },
  { id: "edge-5", source: "email_39da", target: "usr_93f6a2c8", relationship: "linked_to", weight: 0.69 },
  { id: "edge-6", source: "mrc_19db7e41", target: "acct_0041", relationship: "suspicious_connection", weight: 0.81 },
];

export const typologies: FraudTypology[] = [
  {
    id: "typ-mule-burst",
    name: "Mule account burst funding",
    severity: "critical",
    prevalence: 78,
    sharedBy: 17,
    indicators: ["new beneficiary", "rapid transfer chain", "shared device"],
  },
  {
    id: "typ-ato-geo",
    name: "ATO with geo-velocity pivot",
    severity: "high",
    prevalence: 62,
    sharedBy: 12,
    indicators: ["impossible travel", "new device", "failed step-up"],
  },
  {
    id: "typ-refund-loop",
    name: "Merchant refund laundering",
    severity: "high",
    prevalence: 48,
    sharedBy: 8,
    indicators: ["refund loop", "merchant cluster", "AML overlap"],
  },
];

export const heatmap: HeatmapPoint[] = [
  { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792, risk: 91, alerts: 284 },
  { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219, risk: 78, alerts: 166 },
  { city: "Johannesburg", country: "ZA", lat: -26.2041, lng: 28.0473, risk: 72, alerts: 149 },
  { city: "Accra", country: "GH", lat: 5.6037, lng: -0.187, risk: 64, alerts: 98 },
  { city: "Cairo", country: "EG", lat: 30.0444, lng: 31.2357, risk: 58, alerts: 87 },
  { city: "Casablanca", country: "MA", lat: 33.5731, lng: -7.5898, risk: 52, alerts: 76 },
];

export const metrics: OperatingMetrics = {
  fraudDetectionRate: 93.4,
  falsePositiveReduction: 28.6,
  recoveryRate: 71.8,
  decisionLatencyMs: 146,
  analystEfficiencyGain: 41.2,
  eventsPerMinute: 18342,
  blockedValue: 4320000,
  recalledValue: 1180000,
};

export const amlCustomers: AmlCustomerRisk[] = [
  {
    customerId: "cust-9041",
    name: "Corporate remitter hash",
    fraudRisk: 91,
    amlRisk: 82,
    sanctionsRisk: 37,
    unifiedRisk: 86,
    riskLevel: "critical",
    drivers: ["layering route", "mule beneficiary", "high value burst"],
  },
  {
    customerId: "cust-2290",
    name: "Retail wallet hash",
    fraudRisk: 77,
    amlRisk: 53,
    sanctionsRisk: 12,
    unifiedRisk: 68,
    riskLevel: "high",
    drivers: ["ATO indicators", "new device", "rapid beneficiary update"],
  },
  {
    customerId: "cust-7811",
    name: "Merchant network hash",
    fraudRisk: 69,
    amlRisk: 74,
    sanctionsRisk: 21,
    unifiedRisk: 72,
    riskLevel: "high",
    drivers: ["refund loop", "merchant graph", "cash-out pattern"],
  },
];

export const learning: LearningState = {
  modelVersion: "hybrid-risk-2026.07",
  lastRetrainedAt: minutesAgo(60 * 26),
  driftIndex: 0.17,
  labelledCases: 12842,
  falsePositiveRate: 7.8,
  precisionLift: 18.4,
  feedbackQueue: 37,
};

export const audit: AuditEvent[] = [
  {
    id: "aud-1",
    actor: "amara.okafor",
    role: "fraud_investigator",
    action: "payment.recall.requested",
    target: "pay-8GPI-4419",
    metadata: { reason: "critical fraud score", encrypted: true },
    createdAt: minutesAgo(6),
  },
  {
    id: "aud-2",
    actor: "system",
    role: "admin",
    action: "case.auto_created",
    target: "case-2048",
    metadata: { policy: "critical-risk-auto-case-v4" },
    createdAt: minutesAgo(21),
  },
];

export const agentCapabilities: AgentCapability[] = [
  {
    id: "agent-data-analyst",
    name: "Data Analyst Agent",
    category: "data_analysis",
    status: "ready",
    automationRate: 86,
    avgRuntimeSeconds: 34,
    humanReviewRequired: false,
    description: "Runs natural-language investigations across transactions, sessions, merchants, devices, disputes, and cases.",
    examplePrompts: [
      "Identify merchants with a high concentration of shared users.",
      "Show users moving from low-value to high-value merchant activity in the last 30 days.",
    ],
    lastRunAt: minutesAgo(12),
  },
  {
    id: "agent-graph-analyst",
    name: "Graph Analyst Agent",
    category: "fraud_ring_detection",
    status: "ready",
    automationRate: 79,
    avgRuntimeSeconds: 41,
    humanReviewRequired: true,
    description: "Maps connections across users, devices, IPs, emails, merchants, accounts, and payments to surface fraud rings.",
    examplePrompts: [
      "Map shared devices and locations for the top 10 device IDs.",
      "Review email addresses for common merchants and collusion signals.",
    ],
    lastRunAt: minutesAgo(18),
  },
  {
    id: "agent-osint",
    name: "OSINT Search Agent",
    category: "osint",
    status: "ready",
    automationRate: 72,
    avgRuntimeSeconds: 58,
    humanReviewRequired: true,
    description: "Collects public registry, web, adverse media, domain, and ownership signals for EDD and merchant reviews.",
    examplePrompts: ["Perform an OSINT search on [entity_name] and return relevant findings."],
    lastRunAt: minutesAgo(24),
  },
  {
    id: "agent-rule-assistant",
    name: "Rule Assistant Agent",
    category: "rule_optimization",
    status: "ready",
    automationRate: 91,
    avgRuntimeSeconds: 26,
    humanReviewRequired: true,
    description: "Turns plain-language fraud and AML hypotheses into testable monitoring rules with expected fire rates.",
    examplePrompts: [
      "Suggest a rule for merchants under 90 days old with no acquiring transactions and reused devices.",
    ],
    lastRunAt: minutesAgo(9),
  },
  {
    id: "agent-dispute",
    name: "Dispute Filing Agent",
    category: "dispute_management",
    status: "ready",
    automationRate: 83,
    avgRuntimeSeconds: 44,
    humanReviewRequired: true,
    description: "Builds network-ready evidence packages for chargebacks, including Visa Compelling Evidence 3.0 checks.",
    examplePrompts: [
      "Determine whether any disputes qualify for Visa Compelling Evidence 3.0.",
    ],
    lastRunAt: minutesAgo(31),
  },
  {
    id: "agent-aml-ops",
    name: "Agentic AML Ops",
    category: "aml_ops",
    status: "ready",
    automationRate: 88,
    avgRuntimeSeconds: 52,
    humanReviewRequired: true,
    description: "Clears low-risk AML queues, assembles EDD, screens adverse media, and drafts SAR narratives with audit trails.",
    examplePrompts: [
      "Review the last 30 days of activity and identify potential account takeover cases.",
      "Resolve sanctions false positives with customer and transaction context.",
    ],
    lastRunAt: minutesAgo(6),
  },
];

export const agentOpsControlPlane: AgentOpsControlPlane = {
  autonomyMode: "monitored",
  policies: [
    {
      id: "policy-real-time-fraud-defense",
      name: "Real-time fraud defense",
      autonomyMode: "monitored",
      riskThreshold: 72,
      humanApprovalAboveRisk: 88,
      maxAutonomousValue: 25_000,
      allowedActions: ["step_up", "hold_payment", "create_case", "propose_rule"],
      escalationRoles: ["fraud_investigator", "admin"],
      description:
        "Agents can step up or hold moderate-risk activity, but critical or high-value actions require investigator approval.",
    },
    {
      id: "policy-merchant-risk",
      name: "Merchant risk containment",
      autonomyMode: "copilot",
      riskThreshold: 70,
      humanApprovalAboveRisk: 80,
      maxAutonomousValue: 10_000,
      allowedActions: ["propose_rule", "create_case", "share_intelligence"],
      escalationRoles: ["fraud_investigator", "compliance_officer", "admin"],
      description:
        "Merchant collusion and transaction laundering recommendations are generated with evidence and held for review.",
    },
    {
      id: "policy-dispute-evidence",
      name: "Dispute evidence automation",
      autonomyMode: "autonomous",
      riskThreshold: 40,
      humanApprovalAboveRisk: 90,
      maxAutonomousValue: 5_000,
      allowedActions: ["draft_sar", "propose_rule"],
      escalationRoles: ["analyst", "fraud_investigator"],
      description:
        "Agents can assemble dispute and case evidence automatically; filing or enforcement still follows workflow approval.",
    },
  ],
  telemetry: {
    signalsMonitoredDaily: 82_400_000,
    lastCycleAt: minutesAgo(4),
    p95LatencyMs: 142,
    agentPrecision: 92.4,
    falsePositiveReduction: 41.8,
    driftScore: 0.11,
    queuedActions: 3,
    autonomousActionsToday: 127,
    humanApprovalsPending: 2,
    casesCreatedToday: 18,
    paymentValueHeld: 1_840_000,
    rulesProposedToday: 5,
  },
  emergingPatterns: [
    {
      id: "pattern-remote-access-scam",
      name: "Remote access scam sessions before high-value transfer",
      severity: "critical",
      riskScore: 94,
      signals: ["remote_access_tool", "new beneficiary", "behaviour deviation", "high-value transfer"],
      affectedEntities: ["usr_93f6a2c8", "acct_0041", "pay-8GPI-4419"],
      proposedRuleId: "rule-remote-access-transfer-hold",
      firstSeenAt: minutesAgo(47),
      lastSeenAt: minutesAgo(4),
      impactEstimate: "$1.84M payments held before settlement",
      status: "contained",
    },
    {
      id: "pattern-agentic-browser-card-testing",
      name: "Agentic browser automation card testing",
      severity: "high",
      riskScore: 86,
      signals: ["bot_score", "low-value probes", "device fingerprint reuse", "merchant hopping"],
      affectedEntities: ["mrc-velo-184", "mrc-luno-092", "dev-shared-019"],
      proposedRuleId: "rule-agentic-browser-card-testing",
      firstSeenAt: minutesAgo(136),
      lastSeenAt: minutesAgo(12),
      impactEstimate: "3,900 low-value probes suppressed",
      status: "watching",
    },
    {
      id: "pattern-deepfake-onboarding",
      name: "Deepfake-assisted merchant onboarding cluster",
      severity: "high",
      riskScore: 82,
      signals: ["deepfake_risk", "shared operators", "fresh domains", "no acquiring transactions"],
      affectedEntities: ["mrc-atlas-771", "mrc-cape-330"],
      proposedRuleId: "rule-merchant-deepfake-step-up",
      firstSeenAt: minutesAgo(231),
      lastSeenAt: minutesAgo(20),
      impactEstimate: "14 merchant step-up reviews created",
      status: "escalated",
    },
  ],
  actionQueue: [
    {
      id: "act-hold-remote-access-001",
      agentId: "agent-aml-ops",
      type: "hold_payment",
      title: "Hold transfer with remote access scam signals",
      description:
        "Payment was initiated after remote access telemetry, impossible travel, and beneficiary change within 8 minutes.",
      riskScore: 94,
      amount: 184_000,
      status: "executed",
      requiresApproval: false,
      evidence: ["pattern-remote-access-scam", "pay-8GPI-4419", "case-2048"],
      createdAt: minutesAgo(6),
      executedAt: minutesAgo(5),
      approvedBy: "policy-real-time-fraud-defense",
    },
    {
      id: "act-rule-card-testing-002",
      agentId: "agent-rule-assistant",
      type: "propose_rule",
      title: "Deploy agentic browser card-testing rule",
      description:
        "Add a monitor-mode rule for low-value probes, high bot score, and fingerprint reuse across merchants.",
      riskScore: 86,
      status: "requires_approval",
      requiresApproval: true,
      evidence: ["pattern-agentic-browser-card-testing", "rule-agentic-browser-card-testing"],
      createdAt: minutesAgo(12),
    },
    {
      id: "act-share-merchant-003",
      agentId: "agent-graph-analyst",
      type: "share_intelligence",
      title: "Share anonymised merchant collusion package",
      description:
        "Publish HMAC-only collusion package to trusted institutions for merchants sharing users and device infrastructure.",
      riskScore: 91,
      status: "requires_approval",
      requiresApproval: true,
      evidence: ["mrc-velo-184", "mrc-luno-092", "dev-shared-019"],
      createdAt: minutesAgo(17),
    },
  ],
};

export const deploymentReadiness: DeploymentReadiness = {
  environment: process.env.NODE_ENV ?? "development",
  generatedAt: minutesAgo(1),
  status: "warn",
  checks: [
    {
      id: "readiness-api",
      name: "API health and rate limiting",
      status: "pass",
      detail: "NestJS health endpoint, RBAC guard, Helmet, CORS, and throttling are enabled.",
    },
    {
      id: "readiness-secrets",
      name: "Production secret binding",
      status: process.env.CONSORTIUM_SHARED_SECRET ? "pass" : "warn",
      detail: process.env.CONSORTIUM_SHARED_SECRET
        ? "Consortium HMAC and encryption secret is provided by the environment."
        : "Local development secret is in use.",
      remediation: "Set CONSORTIUM_SHARED_SECRET and mount production keys from a vault before launch.",
    },
    {
      id: "readiness-persistence",
      name: "Durable storage adapters",
      status: process.env.DATABASE_URL && process.env.REDIS_URL ? "pass" : "warn",
      detail: process.env.DATABASE_URL && process.env.REDIS_URL
        ? "PostgreSQL and Redis connection strings are configured."
        : "The local demo uses in-memory state until DATABASE_URL and REDIS_URL are configured.",
      remediation: "Run Prisma migrations and connect Redis/Kafka before processing live customer data.",
    },
    {
      id: "readiness-agentops",
      name: "AgentOps governance",
      status: "pass",
      detail: "Agent autonomy modes, approval queues, policy thresholds, telemetry, and audit trails are modeled.",
    },
    {
      id: "readiness-observability",
      name: "Operational telemetry",
      status: "pass",
      detail: "Prometheus-compatible metrics and readiness APIs are exposed for deployment monitoring.",
    },
  ],
};

export const merchantInsights: MerchantRiskInsight[] = [
  {
    merchantId: "mrc-velo-184",
    merchantName: "Velo Digital Goods",
    ageDays: 42,
    sharedUsers: 318,
    linkedMerchants: ["Luno Arcade", "Atlas Voucher Hub", "Northstar Skins"],
    dormantDays: 64,
    sessionSpikePct: 870,
    noAcquiringTransactions: true,
    deviceReuseCount: 23,
    collusionScore: 91,
    riskLevel: "critical",
    findings: [
      "High overlap of user hashes with three merchants that share payout devices.",
      "Dormant for 64 days, then spiked from 7 to 68 sessions per hour.",
      "No acquiring transactions despite checkout sessions and refund attempts.",
    ],
  },
  {
    merchantId: "mrc-luno-092",
    merchantName: "Luno Arcade",
    ageDays: 76,
    sharedUsers: 244,
    linkedMerchants: ["Velo Digital Goods", "Northstar Skins"],
    dormantDays: 61,
    sessionSpikePct: 640,
    noAcquiringTransactions: false,
    deviceReuseCount: 17,
    collusionScore: 84,
    riskLevel: "critical",
    findings: [
      "Shared users moved from low-value card tests to high-value digital purchases.",
      "Same administrative device appeared on two merchant dashboards.",
    ],
  },
  {
    merchantId: "mrc-atlas-771",
    merchantName: "Atlas Voucher Hub",
    ageDays: 28,
    sharedUsers: 189,
    linkedMerchants: ["Velo Digital Goods", "Cape Mobile Trade"],
    dormantDays: 69,
    sessionSpikePct: 512,
    noAcquiringTransactions: true,
    deviceReuseCount: 12,
    collusionScore: 77,
    riskLevel: "high",
    findings: [
      "New merchant with no acquiring history and a reused operator device.",
      "Spike concentrated in VPN-heavy sessions from Lagos and Accra.",
    ],
  },
  {
    merchantId: "mrc-cape-330",
    merchantName: "Cape Mobile Trade",
    ageDays: 118,
    sharedUsers: 143,
    linkedMerchants: ["Atlas Voucher Hub"],
    dormantDays: 60,
    sessionSpikePct: 406,
    noAcquiringTransactions: false,
    deviceReuseCount: 9,
    collusionScore: 68,
    riskLevel: "high",
    findings: [
      "Dormant account resumed with session mix inconsistent with historic business model.",
      "Card testing attempts routed through shared IP range.",
    ],
  },
];

export const sharedDeviceInsights: SharedDeviceInsight[] = [
  {
    deviceId: "dev-fp-88a1",
    sharedUsers: 47,
    locations: [
      { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792, users: 22 },
      { city: "Accra", country: "GH", lat: 5.6037, lng: -0.187, users: 14 },
      { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219, users: 11 },
    ],
    sessionRiskSignals: ["residential proxy", "copy-paste in card fields", "timezone mismatch"],
    linkedMerchants: ["Velo Digital Goods", "Luno Arcade"],
    riskScore: 94,
  },
  {
    deviceId: "dev-fp-19cc",
    sharedUsers: 39,
    locations: [
      { city: "Johannesburg", country: "ZA", lat: -26.2041, lng: 28.0473, users: 18 },
      { city: "Casablanca", country: "MA", lat: 33.5731, lng: -7.5898, users: 9 },
    ],
    sessionRiskSignals: ["headless browser", "payment method cycling", "rapid signups"],
    linkedMerchants: ["Northstar Skins", "Cape Mobile Trade"],
    riskScore: 89,
  },
  {
    deviceId: "dev-fp-73de",
    sharedUsers: 33,
    locations: [
      { city: "Cairo", country: "EG", lat: 30.0444, lng: 31.2357, users: 16 },
      { city: "Lagos", country: "NG", lat: 6.5244, lng: 3.3792, users: 8 },
    ],
    sessionRiskSignals: ["impossible travel", "VPN exit node", "new beneficiary within session"],
    linkedMerchants: ["Atlas Voucher Hub"],
    riskScore: 83,
  },
  {
    deviceId: "dev-fp-0a41",
    sharedUsers: 28,
    locations: [
      { city: "Nairobi", country: "KE", lat: -1.2921, lng: 36.8219, users: 15 },
      { city: "Accra", country: "GH", lat: 5.6037, lng: -0.187, users: 7 },
    ],
    sessionRiskSignals: ["emulator signals", "SIM country mismatch", "bot-like navigation"],
    linkedMerchants: ["Velo Digital Goods"],
    riskScore: 79,
  },
];

export const accountTakeovers: AccountTakeoverInsight[] = [
  {
    userId: "usr_aa19de09",
    accountId: "acct-7782",
    riskScore: 92,
    last30DaySignals: ["new device", "impossible travel", "password reset", "beneficiary update", "failed step-up"],
    firstSeenDevice: "dev-trusted-1102",
    currentDevice: "dev-fp-88a1",
    geographyShift: "Nairobi to Lagos in 43 minutes",
    recommendedAction: "Freeze outbound movement and require assisted identity reverification.",
  },
  {
    userId: "usr_d7bc9011",
    accountId: "acct-4419",
    riskScore: 86,
    last30DaySignals: ["email change", "proxy session", "high-value payout", "device fingerprint collision"],
    firstSeenDevice: "dev-trusted-8840",
    currentDevice: "dev-fp-73de",
    geographyShift: "Accra to Cairo in 61 minutes",
    recommendedAction: "Route to ATO queue and revoke active sessions.",
  },
  {
    userId: "usr_fa22093d",
    accountId: "acct-6641",
    riskScore: 78,
    last30DaySignals: ["remote access tool", "copy-paste in OTP", "changed payout account"],
    firstSeenDevice: "dev-trusted-6620",
    currentDevice: "dev-fp-19cc",
    geographyShift: "Johannesburg to Casablanca in 2 hours",
    recommendedAction: "Hold payout and initiate customer contact.",
  },
];

export const osintFindings: OsintFinding[] = [
  {
    entityName: "Velo Digital Goods",
    riskLevel: "high",
    sourcesChecked: ["business registry", "domain WHOIS", "adverse media", "social web", "sanctions aliases"],
    findings: [
      "Domain registration changed 9 days before session spike.",
      "Declared digital goods category conflicts with observed voucher resale content.",
      "Two linked domains use the same analytics tag and support email hash.",
    ],
    adverseMediaSignals: ["complaint forum references to non-delivery", "high refund chatter"],
    ownershipSignals: ["operator email hash appears on Atlas Voucher Hub", "shared phone hash with prior closed merchant"],
    recommendedAction: "Open EDD review, validate beneficial owner, and restrict settlement until review completes.",
    completedAt: minutesAgo(18),
  },
];

export const disputes: DisputeEvidence[] = [
  {
    disputeId: "disp-visa-3001",
    cardNetwork: "Visa",
    reasonCode: "10.4",
    qualifiesForVisaCE30: true,
    confidence: 91,
    customerId: "cust-2290",
    merchantName: "Velo Digital Goods",
    disputedTransaction: {
      id: "txn-disputed-9901",
      amount: 460,
      occurredAt: minutesAgo(60 * 24 * 4),
    },
    compellingTransactions: [
      {
        id: "txn-ce3-1101",
        amount: 89,
        occurredAt: minutesAgo(60 * 24 * 96),
        deviceId: "dev-fp-88a1",
        ipAddress: "198.51.100.24",
        shippingAddressMatch: true,
        accountLoginMatch: true,
      },
      {
        id: "txn-ce3-1102",
        amount: 112,
        occurredAt: minutesAgo(60 * 24 * 73),
        deviceId: "dev-fp-88a1",
        ipAddress: "198.51.100.24",
        shippingAddressMatch: true,
        accountLoginMatch: true,
      },
      {
        id: "txn-ce3-1103",
        amount: 134,
        occurredAt: minutesAgo(60 * 24 * 41),
        deviceId: "dev-fp-88a1",
        ipAddress: "198.51.100.24",
        shippingAddressMatch: true,
        accountLoginMatch: true,
      },
    ],
    evidenceSummary:
      "Three prior undisputed transactions match account login, device, IP, and shipping evidence for the disputed cardholder.",
  },
  {
    disputeId: "disp-visa-3002",
    cardNetwork: "Visa",
    reasonCode: "10.4",
    qualifiesForVisaCE30: false,
    confidence: 48,
    customerId: "cust-7811",
    merchantName: "Cape Mobile Trade",
    disputedTransaction: {
      id: "txn-disputed-9902",
      amount: 810,
      occurredAt: minutesAgo(60 * 24 * 2),
    },
    compellingTransactions: [],
    evidenceSummary: "No three qualifying prior transactions with consistent device and address evidence were found.",
  },
];

export const lowHighPatterns: LowHighPattern[] = [
  {
    userId: "usr_93f6a2c8",
    lowValueMerchant: "Northstar Skins",
    highValueMerchant: "Velo Digital Goods",
    lowValueAmount: 2.1,
    highValueAmount: 620,
    elapsedHours: 4,
    riskScore: 88,
  },
  {
    userId: "usr_aa19de09",
    lowValueMerchant: "Atlas Voucher Hub",
    highValueMerchant: "Luno Arcade",
    lowValueAmount: 1.4,
    highValueAmount: 475,
    elapsedHours: 7,
    riskScore: 82,
  },
  {
    userId: "usr_d7bc9011",
    lowValueMerchant: "Cape Mobile Trade",
    highValueMerchant: "Velo Digital Goods",
    lowValueAmount: 3.2,
    highValueAmount: 910,
    elapsedHours: 12,
    riskScore: 79,
  },
];

export const suggestedRules: SuggestedRule[] = [
  {
    id: "rule-new-merchant-reused-device",
    name: "New merchant with reused operator device",
    description:
      "Review or hold merchants under 90 days old, with no acquiring transactions, when their device has been used by more than five accounts.",
    logic:
      "merchant.age_days < 90 AND merchant.acquiring_txn_count = 0 AND device.distinct_account_count > 5",
    expectedFireRate: 1.8,
    expectedFalsePositiveReduction: 22,
    action: "review",
    backtestSummary:
      "Backtest across 90 days found 42 merchant events, 31 confirmed risky, and avoided broad review of 1,690 low-risk merchants.",
    lifecycle: "monitor",
  },
  {
    id: "rule-dormant-session-spike",
    name: "Dormant merchant session spike",
    description:
      "Escalate merchants dormant for at least 60 days when session activity rises more than 300 percent and device risk exceeds 70.",
    logic:
      "merchant.dormant_days >= 60 AND session.spike_pct > 300 AND device.risk_score >= 70",
    expectedFireRate: 2.4,
    expectedFalsePositiveReduction: 18,
    action: "step_up",
    backtestSummary:
      "Captured 86 percent of dormant-pivot incidents with 18 percent fewer false positives than a flat volume rule.",
    lifecycle: "monitor",
  },
  {
    id: "rule-remote-access-transfer-hold",
    name: "Remote access transfer hold",
    description:
      "Hold high-value transfers when remote access telemetry appears near a beneficiary change or abnormal session behavior.",
    logic:
      "event.type = 'transaction' AND amount > 25000 AND remote_access_tool = true AND beneficiary.changed_within_minutes <= 15 AND behaviour_deviation > 70",
    expectedFireRate: 0.9,
    expectedFalsePositiveReduction: 31,
    action: "hold",
    backtestSummary:
      "Captured 92 percent of confirmed remote-access scam transfers while keeping legitimate assisted-service sessions below 0.4 percent review rate.",
    lifecycle: "active",
    approvedBy: "policy-real-time-fraud-defense",
    deployedAt: minutesAgo(5),
  },
  {
    id: "rule-agentic-browser-card-testing",
    name: "Agentic browser card-testing suppression",
    description:
      "Step up or block low-value probing patterns produced by automated browser agents across merchants.",
    logic:
      "bot_score > 78 AND device_fingerprint_reuse > 5 AND txn.amount < 5 AND merchant.count_30m > 3",
    expectedFireRate: 2.1,
    expectedFalsePositiveReduction: 27,
    action: "step_up",
    backtestSummary:
      "Suppressed 3,900 low-value probes and reduced downstream dispute exposure by 24 percent in simulation.",
    lifecycle: "draft",
  },
  {
    id: "rule-merchant-deepfake-step-up",
    name: "Deepfake merchant onboarding step-up",
    description:
      "Require enhanced review for new or dormant merchants with deepfake indicators and shared operator infrastructure.",
    logic:
      "merchant.age_days < 120 AND deepfake_risk > 65 AND device.distinct_merchant_count > 2 AND acquiring_txn_count = 0",
    expectedFireRate: 1.4,
    expectedFalsePositiveReduction: 19,
    action: "review",
    backtestSummary:
      "Identified 14 high-risk merchant onboarding clusters with limited impact on established merchants.",
    lifecycle: "draft",
  },
];

export const workforceImpact: WorkforceImpact = {
  manualHoursSavedMonthly: 1280,
  alertsAutoResolvedPct: 74,
  falsePositiveQueueClearedPct: 68,
  estimatedFteRedeployable: 7.4,
  monthlyCostAvoidance: 214000,
  redeploymentRecommendations: [
    "Move L1 reviewers from repetitive false-positive queues into complex investigations and merchant EDD.",
    "Shift operations capacity into rule QA, model governance, and regulatory reporting quality control.",
    "Use agentic dispute evidence collection to reduce manual chargeback assembly work.",
  ],
  technicalFocusAreas: [
    "Real-time payment interdiction tuning",
    "Fraud ring disruption playbooks",
    "Model drift and calibration reviews",
    "Partner and sponsor-bank oversight",
  ],
};

export const demoVideo: DemoVideo = {
  id: "demo-agentic-ops",
  title: "African Guard Agentic Fraud Ops Walkthrough",
  durationSeconds: 390,
  src: "/demo/african-guard-agentic-ops-demo.mp4",
  poster: "/demo/agentic-ops-poster.svg",
  chapters: [
    {
      id: "demo-1",
      title: "Command center orientation",
      timestampSeconds: 0,
      narration: "Start with live risk, queue automation, fraud losses prevented, and team capacity saved.",
      focusArea: "Operating console",
    },
    {
      id: "demo-2",
      title: "Run analyst agents",
      timestampSeconds: 54,
      narration: "Use the Data Analyst, Graph Analyst, OSINT, Dispute, and Rule Assistant agents from one workspace.",
      focusArea: "Agentic workflows",
    },
    {
      id: "demo-3",
      title: "Investigate merchant collusion",
      timestampSeconds: 122,
      narration: "Review shared users, dormant merchant spikes, linked devices, and collusion scores.",
      focusArea: "Merchant risk",
    },
    {
      id: "demo-4",
      title: "Build dispute evidence",
      timestampSeconds: 205,
      narration: "Open the dispute panel to see Visa Compelling Evidence 3.0 qualification and the three supporting transactions.",
      focusArea: "Disputes",
    },
    {
      id: "demo-5",
      title: "Train teams",
      timestampSeconds: 292,
      narration: "Launch guided learning paths or request facilitated training for analysts, investigators, compliance, and partners.",
      focusArea: "Training academy",
    },
  ],
  transcript: [
    "African Guard reduces manual review volume by letting governed AI agents handle repeatable analysis and evidence gathering.",
    "Analysts can ask plain-language questions about merchants, devices, account takeovers, disputes, and transaction patterns.",
    "Every recommendation keeps evidence, confidence, generated rules, and human review controls attached.",
    "Subscriber training paths teach teams how to operate the platform; facilitated remote, onsite, or hybrid training is available for larger deployments.",
  ],
};

export const learningPaths: LearningPath[] = [
  {
    id: "path-fraud-ops",
    title: "Agentic Fraud Ops Certification",
    subscriberTier: "core",
    completionPct: 42,
    certification: "African Guard Certified Fraud Operator",
    lessons: [
      {
        id: "lesson-agent-basics",
        title: "Run safe agent investigations",
        durationMinutes: 18,
        role: "analyst",
        status: "completed",
        objectives: ["Choose the right agent", "Read confidence and evidence", "Escalate when human review is required"],
        simulationPrompt: "Review activity from the last 30 days and identify potential account takeover cases.",
      },
      {
        id: "lesson-merchant-risk",
        title: "Detect merchant collusion and dormant spikes",
        durationMinutes: 24,
        role: "fraud_investigator",
        status: "in_progress",
        objectives: ["Interpret shared-user concentration", "Validate linked merchants", "Apply step-up workflows"],
        simulationPrompt: "Identify merchants that have been dormant in the last 60 days but now show a session spike.",
      },
      {
        id: "lesson-rules",
        title: "Create, backtest, and deploy monitoring rules",
        durationMinutes: 21,
        role: "admin",
        status: "available",
        objectives: ["Convert natural language into logic", "Read fire-rate estimates", "Document rule rationale"],
        simulationPrompt: "Suggest a rule for merchants under 90 days old with no acquiring transactions and reused devices.",
      },
    ],
  },
  {
    id: "path-aml-compliance",
    title: "Agentic AML and Case Governance",
    subscriberTier: "enterprise",
    completionPct: 28,
    certification: "African Guard Certified AML Workflow Owner",
    lessons: [
      {
        id: "lesson-osint",
        title: "OSINT and adverse media review",
        durationMinutes: 27,
        role: "compliance_officer",
        status: "available",
        objectives: ["Run entity research", "Record adverse media rationale", "Attach EDD evidence"],
        simulationPrompt: "Perform an OSINT search on Velo Digital Goods and return relevant findings.",
      },
      {
        id: "lesson-sar",
        title: "SAR narrative and two-eyes review",
        durationMinutes: 31,
        role: "compliance_officer",
        status: "locked",
        objectives: ["Draft SAR narratives", "Use evidence citations", "Route for approval"],
        simulationPrompt: "Summarize the fraud ring case and generate a SAR narrative.",
      },
    ],
  },
];

export const facilitatedTraining: FacilitatedTrainingOffer[] = [
  {
    id: "train-remote",
    title: "Remote analyst onboarding workshop",
    format: "remote",
    duration: "2 half-days",
    audience: "Analysts, fraud investigators, and team leads",
    outcomes: ["Operational readiness", "Agent prompting playbooks", "Queue triage SOP alignment"],
    includesSandbox: true,
  },
  {
    id: "train-onsite",
    title: "Onsite fraud and AML transformation sprint",
    format: "onsite",
    duration: "3 days",
    audience: "Fraud, compliance, product risk, and engineering leadership",
    outcomes: ["Workflow redesign", "Rule library calibration", "Capacity redeployment plan"],
    includesSandbox: true,
  },
  {
    id: "train-hybrid",
    title: "Hybrid sponsor-bank supervision academy",
    format: "hybrid",
    duration: "4 weeks",
    audience: "Sponsor banks, fintech programs, and partner institutions",
    outcomes: ["Program oversight model", "Audit-ready reporting", "Facilitated certification labs"],
    includesSandbox: true,
  },
];

export const recentAgentRuns: AgentRunResult[] = [
  {
    id: "run-merchant-collusion",
    agentId: "agent-graph-analyst",
    prompt: "Identify merchants with a high concentration of shared users and links indicating collusion.",
    status: "needs_review",
    confidence: 91,
    completedAt: minutesAgo(8),
    summary:
      "Four merchants show concentrated shared users, common device infrastructure, and dormant-to-spike behavior consistent with coordinated merchant abuse.",
    findings: [
      "Velo Digital Goods and Luno Arcade share 244 users and 17 operator-device links.",
      "Atlas Voucher Hub is under 90 days old, has no acquiring transactions, and uses a device tied to 12 accounts.",
      "Session spikes are concentrated after 60+ days of dormancy.",
    ],
    recommendedActions: [
      "Open merchant EDD for Velo Digital Goods and Atlas Voucher Hub.",
      "Deploy new-merchant reused-device rule in review mode.",
      "Hold settlement for merchants with collusion score above 85.",
    ],
    generatedRule: suggestedRules[0],
  },
  {
    id: "run-dispute-ce30",
    agentId: "agent-dispute",
    prompt: "Determine whether any disputes qualify for Visa Compelling Evidence 3.0.",
    status: "ready",
    confidence: 91,
    completedAt: minutesAgo(14),
    summary:
      "Dispute disp-visa-3001 qualifies with three prior undisputed transactions that match device, IP, login, and address evidence.",
    findings: [
      "Three qualifying transactions found within the historical window.",
      "Device ID and IP evidence match across the disputed cardholder profile.",
    ],
    recommendedActions: ["Submit CE 3.0 package for disp-visa-3001.", "Keep disp-visa-3002 in manual review."],
    evidencePackageId: "ce30-package-disp-visa-3001",
  },
];

export const tenantOrganisations: TenantOrganisation[] = [
  {
    id: "tenant-afribank",
    name: "AfriBank Group",
    type: "bank",
    country: "NG",
    status: "active",
    isolationKey: "tenant_iso_afb_001",
    mfaRequired: true,
    retentionDays: 2555,
    allowedRoles: ["admin", "fraud_investigator", "analyst", "reviewer", "auditor", "developer"],
  },
  {
    id: "tenant-civic-benefits",
    name: "Civic Benefits Agency",
    type: "government",
    country: "GB",
    status: "active",
    isolationKey: "tenant_iso_cba_002",
    mfaRequired: true,
    retentionDays: 2190,
    allowedRoles: ["admin", "investigator", "reviewer", "auditor"],
  },
  {
    id: "tenant-atlaspay",
    name: "AtlasPay PSP",
    type: "psp",
    country: "ZA",
    status: "onboarding",
    isolationKey: "tenant_iso_psp_003",
    mfaRequired: true,
    retentionDays: 1825,
    allowedRoles: ["admin", "developer", "analyst", "auditor"],
  },
];

export const userAccessProfiles: UserAccessProfile[] = [
  {
    id: "usr-access-admin",
    tenantId: "tenant-afribank",
    name: "Amara Okafor",
    email: "amara.okafor@example.invalid",
    role: "admin",
    permissions: ["integrations:write", "api_keys:write", "cases:approve", "audit:export"],
    scopes: ["transactions:read", "transactions:write", "cases:write", "integrations:admin"],
    mfaEnabled: true,
    lastLoginAt: minutesAgo(18),
  },
  {
    id: "usr-access-investigator",
    tenantId: "tenant-civic-benefits",
    name: "Nadia Mensah",
    email: "nadia.mensah@example.invalid",
    role: "investigator",
    permissions: ["osint:search", "evidence:capture", "cases:write"],
    scopes: ["osint:lawful_basis", "cases:read", "evidence:write"],
    mfaEnabled: true,
    lastLoginAt: minutesAgo(41),
  },
  {
    id: "usr-access-developer",
    tenantId: "tenant-atlaspay",
    name: "Thabo Mbeki",
    email: "thabo.mbeki@example.invalid",
    role: "developer",
    permissions: ["api_keys:write", "webhooks:test", "integrations:test"],
    scopes: ["developer_portal:read", "webhooks:write", "sandbox:write"],
    mfaEnabled: true,
    lastLoginAt: minutesAgo(62),
  },
];

export const paymentNetworkAdapters: PaymentNetworkAdapter[] = [
  {
    id: "adapter-open-banking-uk",
    name: "Open Banking UK / PSD2 AIS-PIS",
    type: "open_banking",
    supportedRails: ["open_banking", "sepa", "rtp"],
    authMethods: ["oauth2", "open_banking_consent", "mtls", "signed_webhook"],
    supportsSandbox: true,
    capabilities: ["account_pull", "transaction_pull", "payment_status", "pre_authorization_score"],
    supportedEvents: ["account.created", "transaction.posted", "payment.initiated", "consent.revoked"],
    rateLimitPerMinute: 600,
    schemaVersion: "ob-3.1.11",
  },
  {
    id: "adapter-visa-risk",
    name: "Visa Risk and Dispute Adapter",
    type: "visa",
    supportedRails: ["visa", "credit_card", "debit_card"],
    authMethods: ["api_key", "mtls", "signed_webhook"],
    supportsSandbox: true,
    capabilities: ["authorization_ingest", "dispute_evidence", "chargeback_status", "token_event_ingest"],
    supportedEvents: ["authorization.requested", "dispute.opened", "token.provisioned", "chargeback.updated"],
    rateLimitPerMinute: 1200,
    schemaVersion: "visa-risk-v1",
  },
  {
    id: "adapter-mastercard-risk",
    name: "Mastercard Risk and Claims Adapter",
    type: "mastercard",
    supportedRails: ["mastercard", "credit_card", "debit_card"],
    authMethods: ["api_key", "mtls", "signed_webhook"],
    supportsSandbox: true,
    capabilities: ["authorization_ingest", "merchant_risk", "claims_ingest", "network_alerts"],
    supportedEvents: ["authorization.requested", "merchant.alerted", "claim.created", "network.risk_signal"],
    rateLimitPerMinute: 1200,
    schemaVersion: "mc-risk-v1",
  },
  {
    id: "adapter-demo-psp",
    name: "African Guard Demo PSP",
    type: "demo_provider",
    supportedRails: ["psp", "visa", "mastercard", "internal"],
    authMethods: ["api_key", "signed_webhook"],
    supportsSandbox: true,
    capabilities: ["transaction_pull", "webhook_replay", "schema_mapping", "error_simulation"],
    supportedEvents: ["transaction.created", "refund.created", "chargeback.created", "merchant.updated"],
    rateLimitPerMinute: 300,
    schemaVersion: "ag-demo-v1",
  },
];

export const integrationConnections: IntegrationConnection[] = [
  {
    id: "int-openbanking-afb",
    tenantId: "tenant-afribank",
    organisationName: "AfriBank Group",
    name: "Open Banking account and payment feed",
    type: "open_banking",
    adapterId: "adapter-open-banking-uk",
    environment: "production",
    authMethods: ["oauth2", "open_banking_consent", "mtls", "signed_webhook"],
    status: "connected",
    scopes: ["accounts:read", "transactions:read", "payments:status", "webhooks:receive"],
    credentialMetadata: {
      secretRef: "vault://tenants/tenant-afribank/integrations/int-openbanking-afb",
      keyFingerprint: "sha256:2f4b:8d31:7aa0",
      encryptedAt: minutesAgo(4400),
      oauthScopes: ["accounts", "transactions", "payments"],
      mtlsCertificateFingerprint: "certfp:af:92:0d:41",
      openBankingConsentId: "consent-ob-829144",
    },
    fieldMappings: [
      { sourceField: "Data.Transaction.TransactionId", targetField: "id", required: true },
      { sourceField: "Data.Transaction.Amount.Amount", targetField: "amount", required: true, transform: "decimal" },
      { sourceField: "Risk.DeviceId", targetField: "deviceId", required: false },
    ],
    webhook: {
      id: "wh-openbanking-afb",
      url: "https://api.africanguard.local/v1/webhooks/int-openbanking-afb",
      events: ["transaction.posted", "payment.initiated", "consent.revoked"],
      status: "active",
      signingSecretRef: "vault://webhooks/int-openbanking-afb/signing",
      lastDeliveryAt: minutesAgo(6),
      failureCount: 0,
    },
    lastSyncAt: minutesAgo(4),
    lastSuccessfulSyncAt: minutesAgo(4),
    dataVolume24h: 184_230,
    totalTransactionsIngested: 12_842_190,
    rateLimitPerMinute: 600,
    retryPolicy: "exponential-backoff: 5 attempts, dead-letter after 15 minutes",
    errors: [],
  },
  {
    id: "int-visa-afb",
    tenantId: "tenant-afribank",
    organisationName: "AfriBank Group",
    name: "Visa authorization and dispute feed",
    type: "visa",
    adapterId: "adapter-visa-risk",
    environment: "production",
    authMethods: ["api_key", "mtls", "signed_webhook"],
    status: "degraded",
    scopes: ["authorization:read", "disputes:read", "disputes:evidence_write"],
    credentialMetadata: {
      secretRef: "vault://tenants/tenant-afribank/integrations/int-visa-afb",
      keyFingerprint: "sha256:91ce:200d:bb18",
      encryptedAt: minutesAgo(9200),
      oauthScopes: [],
      mtlsCertificateFingerprint: "certfp:91:ce:20:0d",
    },
    fieldMappings: [
      { sourceField: "authorizationId", targetField: "id", required: true },
      { sourceField: "cardAcceptor.name", targetField: "merchantId", required: true },
      { sourceField: "risk.deviceFingerprint", targetField: "deviceId", required: false },
    ],
    webhook: {
      id: "wh-visa-afb",
      url: "https://api.africanguard.local/v1/webhooks/int-visa-afb",
      events: ["authorization.requested", "dispute.opened"],
      status: "failing",
      signingSecretRef: "vault://webhooks/int-visa-afb/signing",
      lastDeliveryAt: minutesAgo(24),
      failureCount: 3,
    },
    lastSyncAt: minutesAgo(24),
    lastSuccessfulSyncAt: minutesAgo(49),
    dataVolume24h: 94_800,
    totalTransactionsIngested: 8_441_902,
    rateLimitPerMinute: 1200,
    retryPolicy: "idempotent replay with jitter, poison events to DLQ",
    errors: [
      {
        at: minutesAgo(24),
        code: "WEBHOOK_SIGNATURE_TIMEOUT",
        message: "Webhook signature verification exceeded allowed clock skew.",
        retryable: true,
      },
    ],
  },
  {
    id: "int-demo-atlaspay",
    tenantId: "tenant-atlaspay",
    organisationName: "AtlasPay PSP",
    name: "Sandbox PSP transaction stream",
    type: "demo_provider",
    adapterId: "adapter-demo-psp",
    environment: "sandbox",
    authMethods: ["api_key", "signed_webhook"],
    status: "testing",
    scopes: ["transactions:write", "webhooks:test", "schema_mapping:write"],
    credentialMetadata: {
      secretRef: "vault://tenants/tenant-atlaspay/integrations/int-demo-atlaspay",
      keyFingerprint: "sha256:demo:7e12:90bc",
      encryptedAt: minutesAgo(120),
      oauthScopes: [],
    },
    fieldMappings: [
      { sourceField: "txn_id", targetField: "id", required: true },
      { sourceField: "amount_minor", targetField: "amount", required: true, transform: "minor_units_to_decimal" },
      { sourceField: "buyer.email_hash", targetField: "customerId", required: true },
    ],
    webhook: {
      id: "wh-demo-atlaspay",
      url: "https://api.africanguard.local/v1/webhooks/int-demo-atlaspay",
      events: ["transaction.created", "refund.created", "chargeback.created"],
      status: "active",
      signingSecretRef: "vault://webhooks/int-demo-atlaspay/signing",
      lastDeliveryAt: minutesAgo(2),
      failureCount: 0,
    },
    lastSyncAt: minutesAgo(2),
    lastSuccessfulSyncAt: minutesAgo(2),
    dataVolume24h: 12_420,
    totalTransactionsIngested: 82_144,
    rateLimitPerMinute: 300,
    retryPolicy: "sandbox replay; no production side effects",
    errors: [],
  },
];

export const developerApiKeys: DeveloperApiKey[] = [
  {
    id: "key-afb-server",
    tenantId: "tenant-afribank",
    name: "Production server ingest key",
    prefix: "ag_live_afb_7Jk",
    fingerprint: "sha256:03d4:8bc2:f021",
    scopes: ["transactions:write", "webhooks:read", "cases:read"],
    status: "active",
    createdAt: minutesAgo(18_000),
    lastUsedAt: minutesAgo(2),
    expiresAt: minutesAgo(-120_000),
  },
  {
    id: "key-atlas-sandbox",
    tenantId: "tenant-atlaspay",
    name: "Sandbox integration test key",
    prefix: "ag_test_atlas_2Lm",
    fingerprint: "sha256:8ca0:7ad4:ee19",
    scopes: ["sandbox:write", "transactions:write", "webhooks:test"],
    status: "active",
    createdAt: minutesAgo(340),
    lastUsedAt: minutesAgo(8),
  },
];

export const transactionMonitoringRecords: TransactionMonitoringRecord[] = [
  {
    id: "txn-live-9001",
    tenantId: "tenant-afribank",
    sourceIntegrationId: "int-openbanking-afb",
    rail: "open_banking",
    eventType: "transaction",
    amount: 184_000,
    currency: "USD",
    status: "held",
    customerId: "cust-9041",
    accountId: "acct_0041",
    merchantId: "mrc-velo-184",
    deviceId: "dev-shared-019",
    ipAddress: "198.51.100.24",
    beneficiaryId: "ben-mule-7731",
    riskScore: 94,
    riskLevel: "critical",
    decision: "block",
    reasons: ["remote access scam signal", "new beneficiary", "identity graph risk propagation"],
    explainability: [
      { feature: "remote_access_tool", impact: 24, direction: "risk_increase", evidence: "Remote access detected before transfer." },
      { feature: "identity_graph", impact: 91, direction: "risk_increase", evidence: "Beneficiary linked to mule cluster." },
    ],
    ingestedAt: minutesAgo(5),
    processedAt: minutesAgo(5),
    caseId: "case-2048",
  },
  {
    id: "txn-card-7312",
    tenantId: "tenant-afribank",
    sourceIntegrationId: "int-visa-afb",
    rail: "visa",
    eventType: "transaction",
    amount: 2,
    currency: "USD",
    status: "blocked",
    customerId: "cust-2290",
    cardId: "card_tok_9921",
    merchantId: "mrc-luno-092",
    deviceId: "dev-shared-019",
    ipAddress: "203.0.113.19",
    riskScore: 86,
    riskLevel: "high",
    decision: "block",
    reasons: ["agentic browser or bot automation", "persistent device fingerprint reuse", "merchant hopping"],
    explainability: [
      { feature: "bot_score", impact: 82, direction: "risk_increase", evidence: "Headless browser and low session entropy." },
      { feature: "device_fingerprint_reuse", impact: 18, direction: "risk_increase", evidence: "Device reused across 9 accounts." },
    ],
    ingestedAt: minutesAgo(11),
    processedAt: minutesAgo(11),
  },
  {
    id: "txn-refund-5530",
    tenantId: "tenant-atlaspay",
    sourceIntegrationId: "int-demo-atlaspay",
    rail: "psp",
    eventType: "transaction",
    amount: 770,
    currency: "USD",
    status: "posted",
    customerId: "cust-demo-112",
    merchantId: "mrc-atlas-771",
    deviceId: "dev-demo-552",
    ipAddress: "192.0.2.44",
    riskScore: 73,
    riskLevel: "high",
    decision: "review",
    reasons: ["refund abuse pattern", "suspicious merchant behaviour", "chargeback risk"],
    explainability: [
      { feature: "refund_velocity", impact: 31, direction: "risk_increase", evidence: "Refund count exceeds peer baseline." },
      { feature: "merchant_age", impact: 20, direction: "risk_increase", evidence: "Merchant is under 90 days old." },
    ],
    ingestedAt: minutesAgo(37),
    processedAt: minutesAgo(36),
  },
];

export const evidenceCaptures: EvidenceCapture[] = [
  {
    id: "evcap-public-profile-001",
    tenantId: "tenant-civic-benefits",
    caseId: "case-2051",
    type: "screenshot",
    title: "Public business profile mentioning associated employer",
    sourceUrl: "https://example.invalid/public/profile",
    hash: "sha256:6f8a5c9a2d0e",
    capturedAt: minutesAgo(58),
    capturedBy: "usr-access-investigator",
    chainOfCustody: ["captured", "hashed", "attached_to_case", "review_pending"],
    quality: "needs_verification",
    retentionExpiresAt: minutesAgo(-2190 * 24 * 60),
  },
  {
    id: "evcap-transaction-9001",
    tenantId: "tenant-afribank",
    caseId: "case-2048",
    type: "transaction",
    title: "Held Open Banking payment with mule beneficiary linkage",
    hash: "sha256:1b7d0e998a31",
    capturedAt: minutesAgo(5),
    capturedBy: "system",
    chainOfCustody: ["ingested", "scored", "case_created", "payment_held"],
    quality: "confirmed",
    retentionExpiresAt: minutesAgo(-2555 * 24 * 60),
  },
];

export const osintInvestigationResults: OsintInvestigationResult[] = [
  {
    query: {
      id: "osint-lawful-001",
      tenantId: "tenant-civic-benefits",
      caseId: "case-2051",
      investigatorId: "usr-access-investigator",
      lawfulBasis: "Public task and fraud prevention investigation",
      purpose: "Verify declared identity and possible undeclared business association for an open case.",
      permissionLevel: "enhanced",
      searchedAt: minutesAgo(58),
      query: {
        name: "Amina K.",
        dateOfBirth: "1987-04-12",
        address: "Address hash addr_77b2",
        nationalInsuranceOrReference: "internal-ref-9931",
        phone: "phone_hash_2281",
        email: "email_hash_39da",
        knownAssociates: ["assoc_hash_991", "assoc_hash_337"],
        employerOrBusiness: "Northstar Skins",
        vehicleOrPropertyReference: "property_ref_hash_19a",
      },
      sourcesQueried: ["internal case records", "Companies House-style registry", "public web profile", "licensed address index"],
    },
    matches: [
      {
        id: "match-company-001",
        label: "Northstar Skins director profile",
        entityType: "company",
        confidence: 84,
        quality: "probable",
        source: "licensed business registry",
        sourceUrl: "https://example.invalid/registry/northstar",
        observedAt: minutesAgo(4200),
        summary: "Name, employer, and associate pattern overlap; human verification required before action.",
        needsHumanReview: true,
      },
      {
        id: "match-social-001",
        label: "Open public profile with matching username pattern",
        entityType: "social_profile",
        confidence: 58,
        quality: "needs_verification",
        source: "public web only",
        sourceUrl: "https://example.invalid/public/profile",
        observedAt: minutesAgo(60),
        summary: "Public profile references the business; image and age-range match are uncertain.",
        needsHumanReview: true,
      },
    ],
    relationshipGraph: {
      nodes: [
        { id: "person_hash_amina", type: "user", label: "Subject hash", risk: 62, x: 44, y: 42 },
        { id: "email_39da", type: "email", label: "Email hash", risk: 67, x: 52, y: 62 },
        { id: "mrc_northstar", type: "merchant", label: "Northstar Skins", risk: 76, x: 68, y: 45 },
        { id: "phone_hash_2281", type: "account", label: "Phone hash", risk: 51, x: 32, y: 56 },
      ],
      edges: [
        { id: "osint-e1", source: "person_hash_amina", target: "email_39da", relationship: "linked_to", weight: 0.72 },
        { id: "osint-e2", source: "email_39da", target: "mrc_northstar", relationship: "linked_to", weight: 0.64 },
        { id: "osint-e3", source: "person_hash_amina", target: "phone_hash_2281", relationship: "linked_to", weight: 0.58 },
      ],
    },
    evidence: [evidenceCaptures[0]!],
    safeguards: [
      "Search requires case ID, lawful basis, permission level, and audit trail.",
      "Private, restricted, paywalled, password-protected, or platform-prohibited content is excluded.",
      "Uncertain public-profile matches are labelled needs verification and cannot trigger enforcement alone.",
      "Data minimisation and retention windows are applied per tenant policy.",
    ],
  },
];

export const complianceGovernance: ComplianceGovernance = {
  retentionPolicies: [
    { dataClass: "transaction_monitoring", retentionDays: 2555, lawfulBasis: "AML and fraud prevention obligations" },
    { dataClass: "osint_evidence", retentionDays: 2190, lawfulBasis: "Public task or legitimate fraud investigation basis" },
    { dataClass: "developer_api_logs", retentionDays: 365, lawfulBasis: "Security monitoring and abuse prevention" },
  ],
  dataMinimisationRules: [
    "Use hashed identifiers in consortium payloads.",
    "Store credential metadata and encrypted secret references only.",
    "Limit OSINT searches to approved sources and active case purposes.",
    "Mark uncertain matches as needs verification and require human review.",
  ],
  controls: [
    {
      id: "ctrl-gdpr-dpa",
      framework: "GDPR",
      title: "Data minimisation, retention, auditability, and subject-rights readiness",
      status: "implemented",
      evidence: ["tenant retention policies", "audit export", "OSINT safeguards"],
      owner: "Data Protection Officer",
    },
    {
      id: "ctrl-open-banking",
      framework: "Open Banking",
      title: "Consent-bound account access and mTLS protected callbacks",
      status: "requires_configuration",
      evidence: ["open banking adapter", "consent ID tracking", "mTLS fingerprint metadata"],
      owner: "Integrations Lead",
    },
    {
      id: "ctrl-pci-scope",
      framework: "PCI DSS",
      title: "Tokenized card references and PCI scope minimisation",
      status: "monitoring",
      evidence: ["card token fields only", "no PAN storage", "network adapter segregation"],
      owner: "Security Officer",
    },
    {
      id: "ctrl-access-governance",
      framework: "Access Governance",
      title: "MFA, RBAC, tenant isolation, and audit trail export",
      status: "implemented",
      evidence: ["MFA flags", "role scopes", "tenant isolation keys", "audit logs"],
      owner: "Platform Admin",
    },
  ],
};

export const enterprisePlatform: EnterprisePlatform = {
  tenants: tenantOrganisations,
  users: userAccessProfiles,
  integrations: integrationConnections,
  adapters: paymentNetworkAdapters,
  apiKeys: developerApiKeys,
  transactions: transactionMonitoringRecords,
  osint: osintInvestigationResults,
  evidence: evidenceCaptures,
  governance: complianceGovernance,
  developerPortal: {
    baseUrl: "https://api.africanguard.local",
    openApiUrl: "/v1/openapi.json",
    webhookEvents: [
      "transaction.created",
      "authorization.requested",
      "payment.initiated",
      "refund.created",
      "chargeback.created",
      "case.updated",
    ],
    sandboxAdapters: ["adapter-demo-psp", "adapter-open-banking-uk", "adapter-visa-risk", "adapter-mastercard-risk"],
    sampleRequest:
      "POST /v1/transactions/ingest { integrationId, id, amount, currency, customerId, deviceId, ipAddress, merchantId }",
  },
};
